export const GRAPH_MUTATION_SCHEMA_VERSION = 1;

export const GRAPH_MUTATION_OPS = Object.freeze({
  ADD_HYPEREDGE: "ADD_HYPEREDGE",
  REMOVE_HYPEREDGE: "REMOVE_HYPEREDGE",
  ADD_INCIDENCE: "ADD_INCIDENCE",
  REMOVE_INCIDENCE: "REMOVE_INCIDENCE",
  RENAME_HYPEREDGE: "RENAME_HYPEREDGE",
  RENAME_VERTEX: "RENAME_VERTEX",
  REMOVE_VERTEX_GLOBAL: "REMOVE_VERTEX_GLOBAL",
  SET_HYPEREDGE_WEIGHT: "SET_HYPEREDGE_WEIGHT",
  SET_HYPEREDGE_TIME: "SET_HYPEREDGE_TIME",
  SET_HYPEREDGE_ATTRIBUTE: "SET_HYPEREDGE_ATTRIBUTE",
  REMOVE_HYPEREDGE_ATTRIBUTE: "REMOVE_HYPEREDGE_ATTRIBUTE",
  COMMIT_BATCH_UPDATES: "COMMIT_BATCH_UPDATES",
  CLEAR_GRAPH: "CLEAR_GRAPH",
  UNDO_LAST_MUTATION: "UNDO_LAST_MUTATION",
});

export const EMPTY_HYPEREDGE_POLICIES = Object.freeze({
  ASK: "ask",
  KEEP_EMPTY: "keep_empty",
  REMOVE_EMPTY: "remove_empty",
});

export const PROTOTYPE_POLLUTION_KEYS = new Set(["__proto__", "prototype", "constructor"]);

export function isSupportedGraphMutationOp(type) {
  return Object.values(GRAPH_MUTATION_OPS).includes(type);
}

