import {
  COMMAND_AVAILABILITY,
  COMMAND_CATEGORIES,
  CONFIRMATION,
  MODEL_POLICY,
  REQUIRED_CONTEXT,
  SIDE_EFFECT,
} from "./deterministicNlu/commandCatalogSchema.js";

export const ACTION_INTENT_VISIBILITY = Object.freeze({
  PUBLIC: "public_chat_command",
  INTERNAL: "internal_only",
  DEPRECATED: "deprecated",
  SPEECH_ACT_ONLY: "speech_act_only",
  PANEL_ONLY: "panel_only",
});

export const ACTION_INTENT_REGISTRY_VERSION = "7.3.13";

const publicAction = ({
  id,
  intent,
  title,
  summary,
  category,
  handlerKind,
  sideEffect,
  confirmation,
  requiredContext = [REQUIRED_CONTEXT.NONE],
  examples = [],
  aliases = [],
  patterns = [],
  argumentSlots = [],
  destructive = false,
  modelPolicy = MODEL_POLICY.ALWAYS_DETERMINISTIC,
  availability = COMMAND_AVAILABILITY.CHAT_COMMAND,
  relatedCommandIds = [],
}) => ({
  id,
  intent,
  title,
  summary,
  category,
  handlerKind,
  sideEffect,
  confirmation,
  requiredContext,
  examples,
  aliases,
  patterns,
  argumentSlots,
  destructive,
  modelPolicy,
  availability,
  visibility: ACTION_INTENT_VISIBILITY.PUBLIC,
  deprecated: false,
  internalReason: null,
  relatedCommandIds,
});

const internalAction = (intent, reason, handlerKind = "internal") => ({
  id: `internal.${intent}`,
  intent,
  title: intent,
  summary: reason,
  category: COMMAND_CATEGORIES.CONFIRMATION_CONTROL,
  handlerKind,
  sideEffect: SIDE_EFFECT.READ_ONLY,
  confirmation: CONFIRMATION.NONE,
  requiredContext: [REQUIRED_CONTEXT.NONE],
  examples: [],
  aliases: [],
  destructive: false,
  modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
  availability: COMMAND_AVAILABILITY.READ_ONLY,
  visibility: ACTION_INTENT_VISIBILITY.INTERNAL,
  deprecated: false,
  internalReason: reason,
  relatedCommandIds: [],
});

const speechActOnlyAction = ({
  id,
  intent,
  title,
  summary,
  examples = [],
  aliases = [],
  requiredContext = [REQUIRED_CONTEXT.NONE],
  relatedCommandIds = [],
}) => ({
  id,
  intent,
  title,
  summary,
  category: COMMAND_CATEGORIES.CONFIRMATION_CONTROL,
  handlerKind: "speech_act_only",
  sideEffect: SIDE_EFFECT.CONFIRMATION_CONTROL,
  confirmation: CONFIRMATION.DEPENDS_ON_REPLACEMENT,
  requiredContext,
  examples,
  aliases,
  patterns: [],
  argumentSlots: [],
  destructive: false,
  modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
  availability: COMMAND_AVAILABILITY.READ_ONLY,
  visibility: ACTION_INTENT_VISIBILITY.SPEECH_ACT_ONLY,
  deprecated: false,
  internalReason: "Speech-act control concept; not a standalone planner action.",
  relatedCommandIds,
});

export const ACTION_INTENT_REGISTRY = Object.freeze([
  publicAction({
    id: "files.upload",
    intent: "upload_files",
    title: "Upload or attach files",
    summary: "Opens the assistant file picker. It does not parse or replace the graph until you choose files and request parsing.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "open_file_picker",
    sideEffect: SIDE_EFFECT.FILE_PICKER,
    confirmation: CONFIRMATION.NO_CONFIRMATION_ACTION,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Upload files", "Open the file picker", "Attach files"],
    aliases: ["add files", "choose files", "file picker"],
    relatedCommandIds: ["files.auto-detect", "files.parse-uploaded"],
  }),
  publicAction({
    id: "files.clear-active-batch",
    intent: "clear_uploaded_files",
    title: "Clear the active upload batch",
    summary: "Clears the active assistant upload batch. The parsed graph and manual dashboard inputs are not changed.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "clear_uploaded_files",
    sideEffect: SIDE_EFFECT.DESTRUCTIVE_BATCH_STATE,
    confirmation: CONFIRMATION.IMMEDIATE_BATCH_STATE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Clear the active batch", "Remove the uploaded files"],
    aliases: ["clear active batch", "clear uploaded files", "detach active files"],
    destructive: true,
    relatedCommandIds: ["files.clear-all-batches", "files.view-previous-batch"],
  }),
  publicAction({
    id: "files.clear-all-batches",
    intent: "clear_all_batches",
    title: "Clear all upload batches",
    summary: "Clears every assistant upload batch. This is destructive for batch workspace state, but does not directly clear the current graph.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "clear_all_batches",
    sideEffect: SIDE_EFFECT.DESTRUCTIVE_BATCH_STATE,
    confirmation: CONFIRMATION.IMMEDIATE_BATCH_STATE,
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES],
    examples: ["Clear all batches", "Delete all upload batches"],
    aliases: ["remove all batches", "clear every batch"],
    destructive: true,
    relatedCommandIds: ["files.clear-active-batch"],
  }),
  publicAction({
    id: "files.view-previous-batch",
    intent: "view_previous_batch",
    title: "View the previous batch",
    summary: "Switches the assistant workspace back to the previous upload batch when one exists.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "view_previous_batch",
    sideEffect: SIDE_EFFECT.BATCH_STATE_EDIT,
    confirmation: CONFIRMATION.NO_CONFIRMATION_ACTION,
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES],
    examples: ["View previous batch", "Show the previous batch"],
    aliases: ["open previous batch", "select last batch"],
    relatedCommandIds: ["files.add-to-previous-batch"],
  }),
  publicAction({
    id: "files.add-to-previous-batch",
    intent: "add_to_previous_batch",
    title: "Add files to the previous batch",
    summary: "Merges the active upload batch into the previous batch when both exist.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "add_to_previous_batch",
    sideEffect: SIDE_EFFECT.BATCH_STATE_EDIT,
    confirmation: CONFIRMATION.NO_CONFIRMATION_ACTION,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH, REQUIRED_CONTEXT.UPLOADED_FILES],
    examples: ["Add files to previous batch", "Add these files to the previous batch"],
    aliases: ["merge with previous batch", "append to last batch"],
    relatedCommandIds: ["files.view-previous-batch"],
  }),
  publicAction({
    id: "files.clear-previous-batch",
    intent: "clear_previous_batch",
    title: "Clear the previous batch",
    summary: "Removes the previous assistant upload batch when one exists. It does not directly clear the current graph.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "clear_previous_batch",
    sideEffect: SIDE_EFFECT.DESTRUCTIVE_BATCH_STATE,
    confirmation: CONFIRMATION.IMMEDIATE_BATCH_STATE,
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES],
    examples: ["Clear previous batch", "Remove the previous batch"],
    aliases: ["delete previous batch", "clear last batch"],
    destructive: true,
    relatedCommandIds: ["files.view-previous-batch", "files.clear-all-batches"],
  }),
  publicAction({
    id: "files.use-active-batch",
    intent: "use_active_batch",
    title: "Use the active batch",
    summary: "Keeps the current assistant upload batch active and reports that subsequent file/model/parser actions use it.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "use_active_batch",
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Use active batch", "Use the active batch"],
    aliases: ["keep active batch"],
    relatedCommandIds: ["files.view-previous-batch"],
  }),
  publicAction({
    id: "files.activate-batch-number",
    intent: "activate_batch_number",
    title: "Activate a numbered batch",
    summary: "Switches the assistant workspace to a numbered upload batch when that batch exists.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "activate_batch",
    sideEffect: SIDE_EFFECT.BATCH_STATE_EDIT,
    confirmation: CONFIRMATION.NO_CONFIRMATION_ACTION,
    requiredContext: [REQUIRED_CONTEXT.EXISTING_BATCH],
    examples: ["Activate batch 2", "Switch to batch 3"],
    aliases: ["activate batch", "switch to batch", "select batch"],
    patterns: ["Activate batch <number>", "Switch to batch <number>", "Select batch <number>"],
    argumentSlots: ["batchNumber"],
    relatedCommandIds: ["files.use-active-batch", "files.view-previous-batch"],
  }),
  publicAction({
    id: "files.generate-parser-for-batch",
    intent: "generate_parser_for_batch",
    title: "Generate parser for a numbered batch",
    summary: "Activates a numbered upload batch and then runs the existing parser-generation workflow for that batch.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "activate_batch",
    sideEffect: SIDE_EFFECT.BATCH_STATE_EDIT,
    confirmation: CONFIRMATION.NO_CONFIRMATION_ACTION,
    requiredContext: [REQUIRED_CONTEXT.EXISTING_BATCH, REQUIRED_CONTEXT.VALID_MAPPING_FOR_BATCH],
    examples: ["Generate parser for batch 2", "Create parser for batch 3"],
    aliases: ["generate parser for batch", "create parser for batch"],
    patterns: ["Generate parser for batch <number>", "Create parser for batch <number>"],
    argumentSlots: ["batchNumber"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["files.activate-batch-number", "mapping.generate-parser-from-mapping"],
  }),
  publicAction({
    id: "files.parse-together",
    intent: "parse_together",
    title: "Parse active files together",
    summary: "Marks the active upload batch to be parsed together as one dataset.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "set_batch_parse_mode",
    sideEffect: SIDE_EFFECT.BATCH_STATE_EDIT,
    confirmation: CONFIRMATION.NO_CONFIRMATION_ACTION,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Parse files together", "Treat these files as one dataset"],
    aliases: ["parse together", "one dataset"],
    relatedCommandIds: ["files.parse-separately", "files.parse-uploaded"],
  }),
  publicAction({
    id: "files.parse-separately",
    intent: "parse_separately",
    title: "Parse active files separately",
    summary: "Marks the active upload batch as separate datasets so the dashboard does not silently merge unrelated graphs.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "set_batch_parse_mode",
    sideEffect: SIDE_EFFECT.BATCH_STATE_EDIT,
    confirmation: CONFIRMATION.NO_CONFIRMATION_ACTION,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Parse files separately", "Treat these files as separate datasets"],
    aliases: ["parse separately", "separate datasets"],
    relatedCommandIds: ["files.parse-together"],
  }),
  publicAction({
    id: "files.use-as-new-dataset",
    intent: "use_as_new_dataset",
    title: "Use upload as the new dataset",
    summary: "Explains that the latest upload batch is already isolated as the active new dataset.",
    category: COMMAND_CATEGORIES.FILE_BATCH_MANAGEMENT,
    handlerKind: "use_as_new_dataset",
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Use as new dataset", "Use these files as a new dataset"],
    aliases: ["new dataset", "keep as separate new upload"],
    relatedCommandIds: ["files.parse-uploaded"],
  }),
  publicAction({
    id: "files.auto-detect",
    intent: "auto_detect_uploaded_files",
    title: "Auto-detect uploaded files",
    summary: "Runs deterministic file and format detection for the active assistant upload batch.",
    category: COMMAND_CATEGORIES.DETECTION_PARSING,
    handlerKind: "auto_detect_uploaded_files",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NO_CONFIRMATION_ACTION,
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES],
    examples: ["Auto-detect uploaded files", "Detect the uploaded format"],
    aliases: ["auto detect uploaded files", "auto-detect format", "detect attached files"],
    relatedCommandIds: ["files.parse-uploaded"],
  }),
  publicAction({
    id: "files.parse-uploaded",
    intent: "parse_uploaded_files",
    title: "Parse uploaded files",
    summary: "Parses the active upload batch using the detected or selected route. If this would replace an existing graph, confirmation is staged first.",
    category: COMMAND_CATEGORIES.DETECTION_PARSING,
    handlerKind: "parse_uploaded_files",
    sideEffect: SIDE_EFFECT.GRAPH_APPLY_CONFIRMATION,
    confirmation: CONFIRMATION.APPLY_CONFIRMATION,
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES],
    examples: ["Parse uploaded files", "Parse the uploaded files"],
    aliases: ["process uploaded files", "convert attached files"],
    relatedCommandIds: ["files.auto-detect", "dashboard.input-route"],
  }),
  publicAction({
    id: "files.custom-parser-route",
    intent: "use_uploaded_files_with_custom_parser",
    title: "Use uploaded files with Custom Parser",
    summary: "Routes the active uploaded batch into Custom Parser Studio without running parser code.",
    category: COMMAND_CATEGORIES.DETECTION_PARSING,
    handlerKind: "use_uploaded_files_with_custom_parser",
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES],
    examples: ["Use uploaded files with Custom Parser", "Send these files to Custom Parser"],
    aliases: ["custom parser uploaded files", "route files to custom parser"],
    relatedCommandIds: ["parser.generate-parser", "parser.run-parser"],
  }),
  publicAction({
    id: "mapping.generate-spec",
    intent: "generate_mapping_spec",
    title: "Generate a mapping specification",
    summary: "Creates a DatasetMappingSpec workflow draft from active file previews. If model assist is disabled, it falls back to deterministic mapping.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "generate_mapping_spec",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Generate mapping specification", "Generate mapping spec"],
    aliases: ["map these files", "infer mapping spec"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["mapping.validate", "mapping.auto-repair"],
  }),
  publicAction({
    id: "mapping.validate",
    intent: "validate_mapping",
    title: "Validate the mapping",
    summary: "Validates the active DatasetMappingSpec without parsing or applying a graph.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "validate_mapping",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    examples: ["Validate the mapping", "Check the mapping spec"],
    aliases: ["validate mapping", "check mapping"],
    relatedCommandIds: ["mapping.auto-repair", "mapping.use-repaired"],
  }),
  publicAction({
    id: "mapping.edit",
    intent: "edit_mapping",
    title: "Edit the mapping",
    summary: "Focuses the active DatasetMappingSpec editor so you can review or edit the mapping JSON. It does not apply edited JSON by itself.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "focus_mapping_editor",
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    examples: ["Edit the mapping", "Open the mapping editor"],
    aliases: ["edit mapping", "show mapping editor", "open mapping editor"],
    relatedCommandIds: ["mapping.validate", "mapping.auto-repair"],
  }),
  publicAction({
    id: "mapping.auto-repair",
    intent: "auto_repair_mapping",
    title: "Auto-repair the mapping",
    summary: "Runs deterministic mapping auto-repair on the active mapping revision.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "auto_repair_mapping",
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    examples: ["Auto-repair the mapping", "Repair the mapping"],
    aliases: ["repair mapping", "fix mapping"],
    relatedCommandIds: ["mapping.validate", "mapping.use-repaired"],
  }),
  publicAction({
    id: "mapping.use-deterministic-draft",
    intent: "use_deterministic_draft",
    title: "Use deterministic mapping draft",
    summary: "Applies the stored deterministic mapping draft to the active batch.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "use_deterministic_draft",
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Use deterministic draft", "Use the deterministic mapping draft"],
    aliases: ["apply deterministic draft", "deterministic draft"],
    relatedCommandIds: ["mapping.use-repaired"],
  }),
  publicAction({
    id: "mapping.use-repaired",
    intent: "use_repaired_mapping",
    title: "Use repaired mapping",
    summary: "Applies the stored repaired mapping to the active batch.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "use_repaired_mapping",
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Use repaired mapping", "Use the repaired mapping"],
    aliases: ["apply repaired mapping", "repaired mapping"],
    relatedCommandIds: ["mapping.validate"],
  }),
  publicAction({
    id: "mapping.compare-expected",
    intent: "compare_expected_output",
    title: "Compare expected output",
    summary: "Compares parser or mapping output with a validation/expected-output file when one is available.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "compare_expected_output",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Compare expected output", "Compare with expected output"],
    aliases: ["validate expected output", "expected output comparison"],
    relatedCommandIds: ["grouping.validation-files"],
  }),
  publicAction({
    id: "mapping.export-finetune",
    intent: "export_mapping_finetune",
    title: "Export mapping fine-tuning data",
    summary: "Downloads a local debug/training example for the active mapping workflow.",
    category: COMMAND_CATEGORIES.MAPPINGS_EXPORTS,
    handlerKind: "export_mapping_finetune",
    sideEffect: SIDE_EFFECT.DOWNLOAD_OR_COPY,
    confirmation: CONFIRMATION.DOWNLOAD_OR_COPY,
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    examples: ["Export mapping fine-tuning data", "Export mapping finetune example"],
    aliases: ["mapping training export", "fine tuning export"],
    relatedCommandIds: ["mapping.generate-spec"],
  }),
  publicAction({
    id: "mapping.repair-spec",
    intent: "repair_mapping_spec",
    title: "Repair mapping specification with local assist",
    summary: "Requests a mapping-spec repair workflow for the active batch. Deterministic validation still checks the result.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "run_local_model_task",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Repair mapping spec", "Repair mapping specification"],
    aliases: ["fix mapping spec"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["mapping.validate", "mapping.auto-repair"],
  }),
  publicAction({
    id: "mapping.generate-deterministic",
    intent: "generate_deterministic_mapping",
    title: "Generate deterministic mapping draft",
    summary: "Builds, auto-repairs, and validates a deterministic mapping draft without requiring a local model.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "generate_deterministic_mapping",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Generate deterministic mapping", "Create deterministic mapping draft"],
    aliases: ["deterministic mapping draft"],
    relatedCommandIds: ["mapping.generate-spec", "mapping.use-deterministic-draft"],
  }),
  publicAction({
    id: "mapping.generate-parser-from-mapping",
    intent: "generate_parser_from_mapping",
    title: "Generate parser from mapping",
    summary: "Generates deterministic Custom Parser code from the active validated mapping.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "generate_parser_from_mapping",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    examples: ["Generate parser from mapping", "Build parser from mapping"],
    aliases: ["parser from mapping"],
    relatedCommandIds: ["parser.generate-parser", "mapping.validate"],
  }),
  publicAction({
    id: "mapping.show-repair-notes",
    intent: "show_repair_notes",
    title: "Show mapping repair notes",
    summary: "Shows deterministic mapping auto-repair notes for the active mapping, when notes exist.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "respond",
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Show mapping repair notes", "Show repair notes"],
    aliases: ["mapping repair notes"],
    relatedCommandIds: ["mapping.auto-repair"],
  }),
  publicAction({
    id: "mapping.accept",
    intent: "accept_mapping",
    title: "Accept mapping",
    summary: "Records positive feedback for the active mapping so local training/debug export can include it.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "mapping_feedback",
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    examples: ["Accept mapping", "Accept the mapping"],
    aliases: ["approve mapping"],
    relatedCommandIds: ["mapping.reject", "mapping.export-finetune"],
  }),
  publicAction({
    id: "mapping.reject",
    intent: "reject_mapping",
    title: "Reject mapping",
    summary: "Records negative feedback for the active mapping so local training/debug export can include it.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "mapping_feedback",
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    examples: ["Reject mapping", "Reject the mapping"],
    aliases: ["decline mapping"],
    relatedCommandIds: ["mapping.accept", "mapping.export-finetune"],
  }),
  publicAction({
    id: "mapping.use-workflow",
    intent: "use_mapping_workflow",
    title: "Use mapping workflow",
    summary: "Starts the deterministic mapping workflow for the active upload batch.",
    category: COMMAND_CATEGORIES.MAPPING_VALIDATION_REPAIR,
    handlerKind: "generate_deterministic_mapping",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Use mapping workflow", "Start mapping workflow"],
    aliases: ["mapping workflow"],
    relatedCommandIds: ["mapping.generate-deterministic"],
  }),
  publicAction({
    id: "runtime.connect-local-model",
    intent: "local_model_connect",
    title: "Connect local model",
    summary: "Tests and connects the configured local Ollama runtime. This may contact only local/private endpoints.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "test_local_model",
    sideEffect: SIDE_EFFECT.RUNTIME_CONTROL,
    confirmation: CONFIRMATION.RUNTIME_CONTROL,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Connect local model", "Reconnect Ollama"],
    aliases: ["connect local model", "connect ollama", "reconnect local assistant"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["runtime.list-models", "runtime.diagnostics"],
  }),
  publicAction({
    id: "runtime.disconnect-local-model",
    intent: "local_model_disable",
    title: "Disconnect local assistant",
    summary: "Disables local model assist and keeps deterministic controls available.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "configure_local_model",
    sideEffect: SIDE_EFFECT.RUNTIME_CONTROL,
    confirmation: CONFIRMATION.RUNTIME_CONTROL,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Disconnect local model", "Disable local assistant"],
    aliases: ["turn off local model", "disconnect ollama", "disconnect local assistant"],
    relatedCommandIds: ["runtime.connect-local-model"],
  }),
  publicAction({
    id: "runtime.list-models",
    intent: "local_model_list",
    title: "List installed local models",
    summary: "Lists models reported by the local Ollama runtime when it is reachable.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "list_local_models",
    sideEffect: SIDE_EFFECT.RUNTIME_PROBE,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["List local models", "Show installed local models"],
    aliases: ["list installed models", "show ollama models"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["runtime.connect-local-model"],
  }),
  publicAction({
    id: "runtime.use-model-name",
    intent: "local_model_select",
    title: "Use a local model name",
    summary: "Updates the configured Ollama model name. The next connection or generation request verifies that the named model is installed and reachable.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "set_local_model_name",
    sideEffect: SIDE_EFFECT.RUNTIME_CONTROL,
    confirmation: CONFIRMATION.RUNTIME_CONTROL,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Use model qwen3:8b", "Use model qwen2.5-coder:1.5b"],
    aliases: ["use model"],
    patterns: ["Use model <model name>"],
    argumentSlots: ["modelName"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["runtime.connect-local-model", "runtime.list-models"],
  }),
  publicAction({
    id: "runtime.test-connection",
    intent: "local_model_test",
    title: "Test local model connection",
    summary: "Runs the local model connection test without changing graph, mapping, or parser state.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "test_local_model",
    sideEffect: SIDE_EFFECT.RUNTIME_PROBE,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Test local model connection", "Test Ollama connection"],
    aliases: ["test local model", "test ollama"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["runtime.diagnostics"],
  }),
  publicAction({
    id: "runtime.diagnostics",
    intent: "local_runtime_diagnostics",
    title: "Open runtime diagnostics",
    summary: "Runs and opens the Local Runtime Diagnostics panel.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "run_runtime_diagnostics",
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Run runtime diagnostics", "Run local runtime diagnostics"],
    aliases: ["runtime diagnostics panel", "ollama diagnostics panel"],
    relatedCommandIds: ["runtime.test-direct-ollama", "runtime.test-bridge"],
  }),
  publicAction({
    id: "runtime.test-direct-ollama",
    intent: "local_runtime_test_direct_ollama",
    title: "Test direct Ollama",
    summary: "Runs the diagnostics probe against the direct Ollama endpoint.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "run_runtime_diagnostics",
    sideEffect: SIDE_EFFECT.RUNTIME_PROBE,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Test direct Ollama", "Test direct Ollama connection"],
    aliases: ["direct ollama test"],
    relatedCommandIds: ["runtime.diagnostics"],
  }),
  publicAction({
    id: "runtime.test-bridge",
    intent: "local_runtime_test_bridge",
    title: "Test Local Runtime Bridge",
    summary: "Runs the diagnostics probe against the optional local runtime bridge.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "run_runtime_diagnostics",
    sideEffect: SIDE_EFFECT.RUNTIME_PROBE,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Test Local Runtime Bridge", "Test the bridge"],
    aliases: ["test bridge", "local runtime bridge test"],
    relatedCommandIds: ["runtime.diagnostics"],
  }),
  publicAction({
    id: "runtime.reconnect-bridge",
    intent: "local_model_reconnect_bridge",
    title: "Reconnect using Ollama bridge",
    summary: "Retries the local assistant connection while preferring the local runtime bridge transport.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "test_local_model",
    sideEffect: SIDE_EFFECT.RUNTIME_CONTROL,
    confirmation: CONFIRMATION.RUNTIME_CONTROL,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Use Ollama bridge", "Prefer Ollama bridge"],
    aliases: ["use local bridge", "prefer bridge"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["runtime.connect-local-model", "runtime.test-bridge"],
  }),
  publicAction({
    id: "runtime.enable-local-model",
    intent: "local_model_enable",
    title: "Enable local model assist",
    summary: "Enables local Ollama assist in settings. Deterministic controls continue to work if the runtime is not connected.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "configure_local_model",
    sideEffect: SIDE_EFFECT.RUNTIME_CONTROL,
    confirmation: CONFIRMATION.RUNTIME_CONTROL,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Enable local model", "Turn on local model assist"],
    aliases: ["enable local assistant", "turn on local assistant"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["runtime.connect-local-model", "runtime.disconnect-local-model"],
  }),
  publicAction({
    id: "runtime.test-generation",
    intent: "local_runtime_test_generation",
    title: "Test simple local generation",
    summary: "Runs the Local Runtime Diagnostics simple generation check when a local model name is configured.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "run_runtime_diagnostics",
    sideEffect: SIDE_EFFECT.RUNTIME_PROBE,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.NONE],
    examples: ["Test simple generation", "Run generation test"],
    aliases: ["simple generation test"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["runtime.diagnostics", "runtime.test-connection"],
  }),
  publicAction({
    id: "runtime.generate-parser",
    intent: "local_model_generate_parser",
    title: "Generate parser with local model",
    summary: "Asks the optional local Ollama assistant to help with parser generation, then validates deterministic output before insertion.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "run_local_model_task",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Generate parser with local model", "Create parser with local model"],
    aliases: ["local model parser generation"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["mapping.generate-parser-from-mapping", "runtime.connect-local-model"],
  }),
  publicAction({
    id: "runtime.analyze-file-roles",
    intent: "local_model_analyze_roles",
    title: "Analyze file roles with local model",
    summary: "Asks the optional local Ollama assistant to explain or analyze active file roles without replacing the graph.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "run_local_model_task",
    sideEffect: SIDE_EFFECT.RUNTIME_PROBE,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    examples: ["Explain file roles with local model", "Analyze file roles with local model"],
    aliases: ["local model file roles"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["files.auto-detect", "runtime.connect-local-model"],
  }),
  publicAction({
    id: "runtime.repair-parser",
    intent: "local_model_repair_parser",
    title: "Repair parser with local model",
    summary: "Asks the optional local Ollama assistant to repair current Custom Parser code, then validates before insertion.",
    category: COMMAND_CATEGORIES.LOCAL_MODEL_RUNTIME,
    handlerKind: "run_local_model_task",
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    requiredContext: [REQUIRED_CONTEXT.GENERATED_PARSER],
    examples: ["Repair parser with local model", "Fix parser with local model"],
    aliases: ["local model parser repair"],
    modelPolicy: MODEL_POLICY.DETERMINISTIC_WITH_LOCAL_ASSIST,
    relatedCommandIds: ["parser.run-parser", "runtime.connect-local-model"],
  }),
  publicAction({
    id: "navigation.show-mappings",
    intent: "show_mappings",
    title: "Show mappings",
    summary: "Opens the Mappings section for the current graph, including H2V/V2H/H2H views and the V2V 2-section projection mapping.",
    category: COMMAND_CATEGORIES.MAPPINGS_EXPORTS,
    handlerKind: "switch_section",
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH],
    examples: ["Show mappings", "Open mappings", "Show V2V mapping"],
    aliases: ["view h2v mapping", "show v2h mapping", "show h2h mapping", "show v2v mapping", "view v2v mapping", "open v2v", "display vertex-to-vertex mapping", "show projected graph mapping"],
    relatedCommandIds: ["navigation.show-exports"],
  }),
  publicAction({
    id: "navigation.show-exports",
    intent: "show_exports",
    title: "Show export options",
    summary: "Opens export previews/options for the current graph without downloading a file.",
    category: COMMAND_CATEGORIES.MAPPINGS_EXPORTS,
    handlerKind: "switch_section",
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH],
    examples: ["Show export options", "Open exports"],
    aliases: ["show exports", "export options"],
    relatedCommandIds: ["dashboard.export-preview"],
  }),
  publicAction({
    id: "pending.cancel",
    intent: "pending_cancel",
    title: "Cancel pending action",
    summary: "Cancels a pending confirmation. No staged graph, parser, or batch operation is committed.",
    category: COMMAND_CATEGORIES.CONFIRMATION_CONTROL,
    handlerKind: "pending_cancel",
    sideEffect: SIDE_EFFECT.CONFIRMATION_CONTROL,
    confirmation: CONFIRMATION.PENDING_CONTROL,
    requiredContext: [REQUIRED_CONTEXT.PENDING_ACTION],
    examples: ["Cancel pending action", "Cancel the pending action"],
    aliases: ["cancel confirmation", "cancel staged action"],
    relatedCommandIds: ["pending.confirm"],
  }),
  publicAction({
    id: "pending.confirm",
    intent: "pending_confirm",
    title: "Confirm pending action",
    summary: "Confirms the currently staged action after the app verifies the confirmation is still fresh.",
    category: COMMAND_CATEGORIES.CONFIRMATION_CONTROL,
    handlerKind: "pending_confirm",
    sideEffect: SIDE_EFFECT.CONFIRMATION_CONTROL,
    confirmation: CONFIRMATION.PENDING_CONTROL,
    requiredContext: [REQUIRED_CONTEXT.COMPATIBLE_PENDING_CONFIRMATION],
    examples: ["Confirm pending action", "Confirm the pending action"],
    aliases: ["confirm action", "confirm staged action"],
    relatedCommandIds: ["pending.cancel"],
  }),
  publicAction({
    id: "runtime.stop",
    intent: "runtime_stop",
    title: "Stop active model/runtime work",
    summary: "Stops active local assistant work through the Stop control. If no cancellable request is active, it is a safe no-op with an informative response; it does not undo already committed graph or mapping edits.",
    category: COMMAND_CATEGORIES.CONFIRMATION_CONTROL,
    handlerKind: "runtime_stop",
    sideEffect: SIDE_EFFECT.RUNTIME_CONTROL,
    confirmation: CONFIRMATION.RUNTIME_CONTROL,
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_CANCELLABLE_WORK],
    examples: ["Stop the current request", "Abort the model request"],
    aliases: ["stop", "abort request", "stop active work"],
    relatedCommandIds: ["pending.cancel"],
  }),
  speechActOnlyAction({
    id: "correction.replace-interpretation",
    intent: "correction",
    title: "Correct the last interpretation",
    summary: "Replaces or refines a pending/recent interpretation. The side effect depends on the corrected command.",
    requiredContext: [REQUIRED_CONTEXT.MATCHING_PENDING_OR_RECENT_INTERPRETATION],
    examples: ["Actually, use paper_id instead of title", "I meant authors.csv, not author.csv"],
    aliases: ["actually", "i meant", "no, use"],
    relatedCommandIds: ["pending.cancel"],
  }),
  internalAction("ambiguous_clear", "Clarification-only guard for short unclear destructive commands."),
  internalAction("ambiguous_action", "Clarification-only guard for pronoun actions such as run it/apply that."),
  internalAction("local_runtime_setup_help", "Read-only setup help handled by runtime diagnostics/help UI."),
  internalAction("local_model_status", "Read-only status summary."),
  internalAction("local_model_explain_strategy", "Model-backed explanatory task, not a deterministic command."),
  internalAction("explain_mapping", "Read-only mapping explanation."),
  internalAction("explain_file_roles", "Read-only file-role explanation."),
  internalAction("explain_uploaded_files", "Read-only upload detection explanation."),
  internalAction("compare_datasets", "Read-only batch comparison."),
  internalAction("compare_formats", "Read-only format comparison."),
  internalAction("diagnose_error", "Read-only diagnostics response."),
  internalAction("batch_updates_placeholder", "Panel-only manual feature placeholder."),
  internalAction("freeform_placeholder", "Manual route placeholder."),
  internalAction("switch_tab", "Input route switching is documented through dashboard-control and route-specific Help entries."),
  internalAction("show_graph_preview", "Graph preview navigation is documented through dashboard-control Help entries."),
  internalAction("show_stats", "Statistics navigation is documented through dashboard-control Help entries."),
  internalAction("select_export_preview", "Export preview selection is documented through dashboard-control/export Help entries."),
  internalAction("clear_graph_request", "Graph clearing is documented through the typed graph mutation catalog entry."),
  internalAction("apply_custom_parser_request", "Parser-result application is documented through the typed parser workflow catalog entry."),
  internalAction("run_custom_parser_request", "Custom Parser run is documented through the typed parser workflow catalog entry."),
  internalAction("route_uploaded_files", "Parameterized upload route selection is routed by legacy planner state and route metadata."),
  internalAction("change_visual_limit", "Visualization limit changes are documented through dashboard-control Help entries."),
  internalAction("parse_guidance", "Read-only input-format guidance."),
  internalAction("custom_parser_guidance", "Read-only Custom Parser workflow guidance."),
  internalAction("visualization_guidance", "Read-only visualization guidance."),
  internalAction("export_guidance", "Read-only export guidance."),
  internalAction("explain_concept", "Read-only format/concept explanation."),
  internalAction("help", "General Help fallback; catalog-specific Help is handled by help_query."),
  internalAction("ambiguous_edge_list_export", "Clarification-only guard for ambiguous edge-list export requests."),
  internalAction("external_ai_prompt", "AI Prompt route copy/preparation is documented by dashboard/export Help and never calls an external API."),
]);

export const PUBLIC_ACTION_INTENTS = Object.freeze(
  ACTION_INTENT_REGISTRY.filter(item => item.visibility === ACTION_INTENT_VISIBILITY.PUBLIC).map(item => item.intent),
);

export const INTERNAL_ACTION_INTENTS = Object.freeze(
  ACTION_INTENT_REGISTRY.filter(item => item.visibility === ACTION_INTENT_VISIBILITY.INTERNAL).map(item => item.intent),
);

export const DEPRECATED_ACTION_INTENTS = Object.freeze(
  ACTION_INTENT_REGISTRY.filter(item => item.visibility === ACTION_INTENT_VISIBILITY.DEPRECATED).map(item => item.intent),
);

export const SPEECH_ACT_ONLY_INTENTS = Object.freeze(
  ACTION_INTENT_REGISTRY.filter(item => item.visibility === ACTION_INTENT_VISIBILITY.SPEECH_ACT_ONLY).map(item => item.intent),
);

export const LEGACY_CONTROL_INTENTS = Object.freeze(
  ACTION_INTENT_REGISTRY
    .filter(item => ![
      ACTION_INTENT_VISIBILITY.DEPRECATED,
      ACTION_INTENT_VISIBILITY.SPEECH_ACT_ONLY,
      ACTION_INTENT_VISIBILITY.PANEL_ONLY,
    ].includes(item.visibility))
    .map(item => item.intent),
);

export const PUBLIC_ACTION_INTENT_SET = new Set(PUBLIC_ACTION_INTENTS);
export const LEGACY_CONTROL_INTENT_SET = new Set(LEGACY_CONTROL_INTENTS);

export function getActionIntentByIntent(intent) {
  return ACTION_INTENT_REGISTRY.find(item => item.intent === intent) ?? null;
}

export function getActionIntentById(id) {
  return ACTION_INTENT_REGISTRY.find(item => item.id === id) ?? null;
}

export function resolvePublicActionIntentReference(action = {}) {
  if (!action || typeof action !== "object") {
    return { valid: false, entry: null, reason: "legacy_action_unregistered" };
  }
  const publicEntries = ACTION_INTENT_REGISTRY.filter(
    item => item.visibility === ACTION_INTENT_VISIBILITY.PUBLIC,
  );
  const references = [
    action.registryId ? { key: "registryId", value: action.registryId } : null,
    action.intent ? { key: "intent", value: action.intent } : null,
    action.handlerKind ? { key: "handlerKind", value: action.handlerKind } : null,
    action.kind ? { key: "kind", value: action.kind } : null,
  ].filter(Boolean);
  if (!references.length) {
    return { valid: false, entry: null, reason: "legacy_action_unregistered" };
  }
  const matchesReference = (entry, reference) => {
    if (reference.key === "registryId") return entry.id === reference.value;
    if (reference.key === "intent") return entry.intent === reference.value;
    if (reference.key === "handlerKind") return entry.handlerKind === reference.value;
    return [entry.id, entry.intent, entry.handlerKind].includes(reference.value);
  };
  const matches = publicEntries.filter(entry => references.every(reference => matchesReference(entry, reference)));
  if (matches.length === 1) return { valid: true, entry: matches[0], reason: null };

  const recognized = references.some(reference => publicEntries.some(entry => matchesReference(entry, reference)));
  return {
    valid: false,
    entry: null,
    reason: recognized ? "legacy_action_identity_mismatch" : "legacy_action_unregistered",
  };
}

export function isPublicActionIntent(intent) {
  return PUBLIC_ACTION_INTENT_SET.has(intent);
}

export function normalizeActionPhrase(text = "") {
  return String(text ?? "")
    .toLowerCase()
    .replace(/[“”]/g, "\"")
    .replace(/[‘’`]/g, "'")
    .replace(/^\s*(?:please\s+)?(?:can|could|would|will)\s+you\s+(?:please\s+)?/i, "")
    .replace(/^\s*(?:go\s+ahead\s+and|i\s+want\s+you\s+to)\s+/i, "")
    .replace(/^\s*please\s+/i, "")
    .replace(/[.!?]+$/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function placeholderPatternToRegExp(pattern = "") {
  const normalized = normalizeActionPhrase(pattern);
  if (!normalized.includes("<")) return null;
  const escaped = normalized.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const withSlots = escaped
    .replace(/<number>/g, "(?<number>\\d+)")
    .replace(/<model name>/g, "(?<modelName>.+)")
    .replace(/<format>/g, "(?<format>.+)")
    .replace(/<route>/g, "(?<route>.+)")
    .replace(/<filename>/g, "(?<filename>.+)");
  return new RegExp(`^${withSlots}$`, "i");
}

export function extractActionArguments(action, text = "") {
  const normalized = normalizeActionPhrase(text);
  const result = {};
  for (const pattern of action?.patterns ?? []) {
    const regex = placeholderPatternToRegExp(pattern);
    if (!regex) continue;
    const match = normalized.match(regex);
    if (!match) continue;
    if (match.groups?.number) result.batchNumber = Number(match.groups.number);
    if (match.groups?.modelName) result.modelName = match.groups.modelName.trim();
    if (match.groups?.format) result.format = match.groups.format.trim();
    if (match.groups?.route) result.route = match.groups.route.trim();
    if (match.groups?.filename) result.filename = match.groups.filename.trim();
    return result;
  }
  const batch = normalized.match(/\bbatch\s+(\d+)\b/);
  if (batch) result.batchNumber = Number(batch[1]);
  const model = normalized.match(/^use model\s+(.+)$/i);
  if (model) result.modelName = model[1].trim();
  return result;
}

export function findActionIntentForText(text = "") {
  const normalized = normalizeActionPhrase(text);
  if (!normalized) return null;
  return ACTION_INTENT_REGISTRY.find(item => {
    if (item.visibility !== ACTION_INTENT_VISIBILITY.PUBLIC) return false;
    const phrases = [...(item.examples ?? []), ...(item.aliases ?? [])].map(normalizeActionPhrase);
    if (phrases.includes(normalized)) return true;
    return (item.patterns ?? []).some(pattern => placeholderPatternToRegExp(pattern)?.test(normalized));
  }) ?? null;
}
