export const DATASET_MAPPING_PATCH_TASK = "plan_dataset_mapping_patch";

export const DATASET_MAPPING_PATCH_OPS = Object.freeze([
  "SET_PARSE_MODE",
  "CREATE_GROUP",
  "RENAME_GROUP",
  "MOVE_FILE_TO_GROUP",
  "SET_FILE_ROLE",
  "SET_FILE_INPUT_USAGE",
  "SET_FILE_KEY_COLUMNS",
  "SET_FILE_LIST_COLUMN",
  "SET_VERTEX_ENTITY_RULE",
  "SET_HYPEREDGE_ENTITY_RULE",
  "ADD_RELATIONSHIP",
  "UPDATE_RELATIONSHIP",
  "REMOVE_RELATIONSHIP",
  "ADD_FILTER",
  "UPDATE_FILTER",
  "REMOVE_FILTER",
  "SET_POLICY",
  "MARK_VALIDATION_FILE",
  "MARK_UPDATE_STREAM",
  "IGNORE_FILE",
  "REMOVE_ASSUMPTION",
  "ADD_ASSUMPTION",
]);

export const DATASET_MAPPING_PATCH_SCHEMA = Object.freeze({
  type: "object",
  additionalProperties: false,
  required: ["task", "classification", "summary", "operations", "clarificationQuestion", "confidence"],
  properties: {
    task: { type: "string", enum: [DATASET_MAPPING_PATCH_TASK] },
    classification: { type: "string", enum: ["patch", "clarification", "not_mapping"] },
    summary: { type: "string" },
    clarificationQuestion: { type: ["string", "null"] },
    confidence: { type: "string", enum: ["low", "medium", "high"] },
    operations: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["type"],
        properties: {
          type: { type: "string", enum: DATASET_MAPPING_PATCH_OPS },
          groupId: { type: ["string", "null"] },
          groupLabel: { type: ["string", "null"] },
          fileName: { type: ["string", "null"] },
          role: { type: ["string", "null"] },
          useAsInput: { type: ["boolean", "null"] },
          keyColumns: { type: "array", items: { type: "string" } },
          sourceFile: { type: ["string", "null"] },
          sourceColumns: { type: "array", items: { type: "string" } },
          targetFile: { type: ["string", "null"] },
          targetColumns: { type: "array", items: { type: "string" } },
          vertexSourceFile: { type: ["string", "null"] },
          vertexColumns: { type: "array", items: { type: "string" } },
          labelColumn: { type: ["string", "null"] },
          timeColumn: { type: ["string", "null"] },
          weightColumn: { type: ["string", "null"] },
          attributes: { type: "array", items: { type: "string" } },
          listColumn: { type: ["string", "null"] },
          listDelimiter: { type: ["string", "null"] },
          policy: { type: ["string", "null"] },
          value: {},
          filter: { type: ["object", "null"] },
          relationship: { type: ["object", "null"] },
          assumption: { type: ["string", "null"] },
        },
      },
    },
  },
});
