import { GRAPH_MUTATION_OPS } from "../../graph/graphMutationSchema.js";
import { DATASET_MAPPING_PATCH_OPS } from "../datasetMappingPatchSchema.js";
import { ALGORITHM_REGISTRY } from "../../algorithms/registry.js";
import { EXPORT_PREVIEWS, ROUTE_REGISTRY } from "../routeRegistry.js";
import { ACTION_INTENT_REGISTRY, ACTION_INTENT_VISIBILITY } from "../actionIntentRegistry.js";
import { PARSER_WORKFLOW_OPERATION_TYPES as SOURCE_PARSER_WORKFLOW_OPERATION_TYPES } from "./domains/parserWorkflowGrammar.js";
import { DASHBOARD_CANONICAL_INTENTS as SOURCE_DASHBOARD_CANONICAL_INTENTS } from "./domains/dashboardActionGrammar.js";
import { isHelpSeekingQuestionText } from "./helpSeekingGuards.js";
import {
  COMMAND_AVAILABILITY,
  COMMAND_CATEGORIES,
  CONFIRMATION,
  MODEL_POLICY,
  REQUIRED_CONTEXT,
  SIDE_EFFECT,
  TYPED_KINDS,
} from "./commandCatalogSchema.js";

const graphExample = (text, expectedOperations, extra = {}) => ({
  text,
  fixture: extra.fixture ?? "graph.basic",
  expectedDomain: "graph_mutation",
  expectedTypedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
  expectedSpeechAct: extra.expectedSpeechAct ?? "imperative_request",
  expectedSideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
  expectedOperations,
  ...extra,
});

const mappingExample = (text, expectedOperationTypes, extra = {}) => ({
  text,
  fixture: extra.fixture ?? "mapping.authorship",
  expectedDomain: extra.expectedDomain ?? "dataset_mapping",
  expectedTypedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
  expectedSpeechAct: extra.expectedSpeechAct ?? "imperative_request",
  expectedSideEffect: extra.expectedSideEffect ?? SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
  expectedOperationTypes,
  ...extra,
});

const parserExample = (text, expectedOperationTypes, extra = {}) => ({
  text,
  fixture: extra.fixture ?? "parser.plan_ready",
  expectedDomain: "parser_workflow",
  expectedTypedKind: TYPED_KINDS.PARSER_WORKFLOW_OPERATION,
  expectedSpeechAct: extra.expectedSpeechAct ?? "imperative_request",
  expectedSideEffect: extra.expectedSideEffect ?? SIDE_EFFECT.WORKFLOW_PREPARATION,
  expectedOperationTypes,
  ...extra,
});

const dashboardExample = (text, expectedIntent, expectedSlots = {}, extra = {}) => ({
  text,
  fixture: extra.fixture ?? "dashboard.basic",
  expectedDomain: "dashboard_control",
  expectedTypedKind: TYPED_KINDS.DASHBOARD_CONTROL_INTENT,
  expectedSpeechAct: extra.expectedSpeechAct ?? "imperative_request",
  expectedSideEffect: SIDE_EFFECT.NAVIGATION,
  expectedIntent,
  expectedSlots,
  ...extra,
});

const legacyExample = (text, expectedIntent, extra = {}) => ({
  text,
  fixture: extra.fixture ?? "dashboard.basic",
  expectedDomain: "legacy_action",
  expectedTypedKind: TYPED_KINDS.LEGACY_ACTION_INTENT,
  expectedSpeechAct: extra.expectedSpeechAct ?? "imperative_request",
  expectedSideEffect: extra.expectedSideEffect,
  expectedIntent,
  expectedOperationTypes: [expectedIntent],
  ...extra,
});

const helpExample = (text, expectedIntent, extra = {}) => ({
  text,
  fixture: extra.fixture ?? "empty",
  expectedDomain: "help_query",
  expectedTypedKind: TYPED_KINDS.HELP_QUERY,
  expectedSpeechAct: extra.expectedSpeechAct ?? expectedHelpSpeechAct(text),
  expectedSideEffect: SIDE_EFFECT.READ_ONLY,
  expectedIntent,
  ...extra,
});

function expectedHelpSpeechAct(text = "") {
  if (isHelpSeekingQuestionText(text)) return "help_seeking_question";
  if (/^\s*(?:how|why)\b/i.test(text)) return "explanation_question";
  if (/^\s*show\b/i.test(text)) return "imperative_request";
  return "informational_question";
}

function expectedLegacySpeechAct(text = "", intent = "") {
  if (intent === "correction") return "correction";
  if (/^\s*(?:stop|cancel|abort)\b/i.test(text)) return "cancellation";
  return "imperative_request";
}

const readOnlyExample = (text, sourceDomain, expectedIntent, extra = {}) => ({
  text,
  fixture: extra.fixture ?? "mapping.authorship",
  expectedDomain: "grounded_question",
  sourceDomain,
  expectedTypedKind: TYPED_KINDS.GROUNDED_QUESTION,
  expectedSpeechAct: extra.expectedSpeechAct ?? "hypothetical_question",
  expectedSideEffect: SIDE_EFFECT.READ_ONLY,
  expectedIntent,
  ...extra,
});

export const CATALOG_VERSION = "7.3.7";
export const CATALOG_CURRENT_VERSION = "7.3.13";

export const DETERMINISTIC_GRAPH_OPERATION_TYPES = Object.freeze([
  GRAPH_MUTATION_OPS.ADD_HYPEREDGE,
  GRAPH_MUTATION_OPS.REMOVE_HYPEREDGE,
  GRAPH_MUTATION_OPS.ADD_INCIDENCE,
  GRAPH_MUTATION_OPS.REMOVE_INCIDENCE,
  GRAPH_MUTATION_OPS.REMOVE_VERTEX_GLOBAL,
  GRAPH_MUTATION_OPS.RENAME_HYPEREDGE,
  GRAPH_MUTATION_OPS.RENAME_VERTEX,
  GRAPH_MUTATION_OPS.SET_HYPEREDGE_TIME,
  GRAPH_MUTATION_OPS.SET_HYPEREDGE_WEIGHT,
  GRAPH_MUTATION_OPS.SET_HYPEREDGE_ATTRIBUTE,
  GRAPH_MUTATION_OPS.REMOVE_HYPEREDGE_ATTRIBUTE,
  GRAPH_MUTATION_OPS.CLEAR_GRAPH,
  GRAPH_MUTATION_OPS.UNDO_LAST_MUTATION,
]);

export const PANEL_ONLY_GRAPH_OPERATION_TYPES = Object.freeze([
  GRAPH_MUTATION_OPS.COMMIT_BATCH_UPDATES,
]);

export const DETERMINISTIC_MAPPING_OPERATION_TYPES = Object.freeze([
  "SET_FILE_ROLE",
  "SET_FILE_KEY_COLUMNS",
  "SET_VERTEX_ENTITY_RULE",
  "SET_HYPEREDGE_ENTITY_RULE",
  "ADD_RELATIONSHIP",
  "SET_POLICY",
  "SET_PARSE_MODE",
  "CREATE_GROUP",
  "MOVE_FILE_TO_GROUP",
  "MARK_VALIDATION_FILE",
  "MARK_UPDATE_STREAM",
  "IGNORE_FILE",
]);

export const PANEL_ONLY_MAPPING_OPERATION_TYPES = Object.freeze(
  DATASET_MAPPING_PATCH_OPS.filter(type => !DETERMINISTIC_MAPPING_OPERATION_TYPES.includes(type)),
);

export const PARSER_WORKFLOW_OPERATION_TYPES = SOURCE_PARSER_WORKFLOW_OPERATION_TYPES;

export const DASHBOARD_CANONICAL_INTENTS = SOURCE_DASHBOARD_CANONICAL_INTENTS;

export const INPUT_FORMAT_REFERENCES = Object.freeze([
  {
    id: "format.h2v",
    name: "H2V / Simple",
    routeLabel: ROUTE_REGISTRY.h2v.label,
    formatId: ROUTE_REGISTRY.h2v.formatId,
    example: "h0: 1 2 3\nh1: 2 4",
    expectations: "Each row names one hyperedge and lists the vertices it contains.",
    autoDetect: true,
    relatedCommand: "Use H2V input",
  },
  {
    id: "format.v2h",
    name: "V2H",
    routeLabel: ROUTE_REGISTRY.v2h.label,
    formatId: ROUTE_REGISTRY.v2h.formatId,
    example: "1: h0 h2\n2: h0 h1",
    expectations: "Each row names one vertex and lists the hyperedges that contain it.",
    autoDetect: true,
    relatedCommand: "Use V2H input",
  },
  {
    id: "format.h2h",
    name: "H2H",
    routeLabel: ROUTE_REGISTRY.h2h.label,
    formatId: ROUTE_REGISTRY.h2h.formatId,
    example: "h0: h1[shared: 2], h2[shared: 1,3]",
    expectations: "Projection rows list neighboring hyperedges and their shared vertices.",
    autoDetect: false,
    relatedCommand: "Use H2H input",
  },
  {
    id: "format.incidence",
    name: "Incidence Edge List",
    routeLabel: ROUTE_REGISTRY.incidence.label,
    formatId: ROUTE_REGISTRY.incidence.formatId,
    example: "h0,1\nh0,2\nh1,2",
    expectations: "Each row is one hyperedge/vertex membership. Optional time and weight columns may follow.",
    autoDetect: true,
    relatedCommand: "Use incidence input",
  },
  {
    id: "format.csv",
    name: "CSV",
    routeLabel: ROUTE_REGISTRY.csv.label,
    formatId: ROUTE_REGISTRY.csv.formatId,
    example: "1,2,3\n2,4",
    expectations: "Each delimited row becomes one hyperedge; row values are vertices.",
    autoDetect: true,
    relatedCommand: "Use CSV input",
  },
  {
    id: "format.edge-list",
    name: "Graph Edge List",
    routeLabel: ROUTE_REGISTRY.edge_list.label,
    formatId: ROUTE_REGISTRY.edge_list.formatId,
    example: "1 2\n2 3",
    expectations: "Each pairwise row becomes a size-two hyperedge, so this is graph-edge-list semantics.",
    autoDetect: true,
    relatedCommand: "Use edge list input",
  },
  {
    id: "format.json",
    name: "JSON",
    routeLabel: ROUTE_REGISTRY.json.label,
    formatId: ROUTE_REGISTRY.json.formatId,
    example: "[{\"id\":\"h0\",\"vertices\":[\"1\",\"2\"]}]",
    expectations: "Accepts an array of {id, vertices} objects or the app canonical hypergraph object.",
    autoDetect: true,
    relatedCommand: "Use JSON input",
  },
  {
    id: "format.cornell",
    name: "Cornell / SNAP",
    routeLabel: ROUTE_REGISTRY.cornell.label,
    formatId: ROUTE_REGISTRY.cornell.formatId,
    example: "nverts.txt: 3, 2\nsimplices.txt: 1, 2, 3, 2, 4",
    expectations: "Uses nverts and simplices files, optionally with times.",
    autoDetect: true,
    relatedCommand: "Switch to Cornell/SNAP",
  },
  {
    id: "format.csr-json",
    name: "CSR JSON",
    routeLabel: ROUTE_REGISTRY.csr.label,
    formatId: ROUTE_REGISTRY.csr.formatId,
    example: "{\"vertexIds\":[\"1\"],\"h2vCSR\":{\"offsets\":[0,1],\"indices\":[0]}}",
    expectations: "Uses vertexIds plus h2vCSR offsets and indices.",
    autoDetect: true,
    relatedCommand: "Use CSR input",
  },
  {
    id: "format.csr-csc-csv",
    name: "CSR / CSC CSV",
    routeLabel: ROUTE_REGISTRY.csc_csv.label,
    formatId: ROUTE_REGISTRY.csc_csv.formatId,
    example: "vertexIds,1,2\nhyperedgeIds,h0\nrowOffsets,0,2\ncolumnIndices,0,1",
    expectations: "Uses labeled rows such as vertexIds, hyperedgeIds, rowOffsets, and columnIndices.",
    autoDetect: true,
    relatedCommand: "Use CSC input",
  },
  {
    id: "format.adjacency-list",
    name: "Adjacency List",
    routeLabel: ROUTE_REGISTRY.adjlist.label,
    formatId: ROUTE_REGISTRY.adjlist.formatId,
    example: "1: 2 3\n2: 1 4",
    expectations: "Each node lists neighbors; reverse duplicate pairs are treated as one undirected size-two hyperedge.",
    autoDetect: true,
    relatedCommand: "Use adjacency list input",
  },
  {
    id: "format.freeform",
    name: "Freeform / NLP",
    routeLabel: ROUTE_REGISTRY.freeform.label,
    formatId: ROUTE_REGISTRY.freeform.formatId,
    example: "Paper 1 has Alice, Bob, and Charlie as co-authors.",
    expectations: "Uses local deterministic extraction only; it does not call an online model.",
    autoDetect: false,
    relatedCommand: "Use Freeform input",
  },
  {
    id: "format.custom-parser",
    name: "Custom Parser",
    routeLabel: ROUTE_REGISTRY.custom_parser.label,
    formatId: ROUTE_REGISTRY.custom_parser.formatId,
    example: "async function parseHypergraph(files, helpers) { return []; }",
    expectations: "For unusual or multi-file inputs: upload files, edit parser code, run, validate, then apply.",
    autoDetect: false,
    relatedCommand: "Open Custom Parser",
  },
  {
    id: "format.ai-prompt",
    name: "AI Prompt",
    routeLabel: ROUTE_REGISTRY.ai_prompt.label,
    formatId: ROUTE_REGISTRY.ai_prompt.formatId,
    example: "Paste graph-like text, choose a target, and copy the generated prompt.",
    expectations: "Prepares a prompt for manual external use; the app does not call cloud APIs.",
    autoDetect: false,
    relatedCommand: "Open AI Prompt",
  },
]);

function legacyActionCatalogEntries() {
  return ACTION_INTENT_REGISTRY
    .filter(action => action.visibility === ACTION_INTENT_VISIBILITY.PUBLIC)
    .map(action => ({
      id: action.id,
      category: action.category,
      domain: "legacy_action",
      intent: action.intent,
      typedKind: TYPED_KINDS.LEGACY_ACTION_INTENT,
      operationTypes: [action.intent],
      title: action.title,
      summary: `${action.summary} To learn about this command, ask “How do I ${action.aliases?.[0] ?? action.title.toLowerCase()}?” To execute it, use a direct request such as “${action.examples?.[0] ?? action.title}.”`,
      patterns: [...(action.patterns ?? []), ...(action.aliases ?? [])],
      examples: (action.examples ?? []).map(text => legacyExample(text, action.intent, {
        expectedSideEffect: action.sideEffect,
        expectedSpeechAct: expectedLegacySpeechAct(text, action.intent),
      })),
      requiredContext: action.requiredContext,
      sideEffect: action.sideEffect,
      confirmation: action.confirmation,
      reversible: !action.destructive,
      destructive: action.destructive,
      worksOffline: true,
      modelPolicy: action.modelPolicy,
      ambiguityNotes: action.destructive
        ? ["This action changes assistant workspace state. Ask as a How-do-I question to learn about it without executing it."]
        : ["Help-seeking forms are read-only; direct requests use the existing deterministic handler."],
      identifierNotes: [],
      relatedCommandIds: action.relatedCommandIds,
      availability: action.availability,
      sinceVersion: CATALOG_CURRENT_VERSION,
    }));
}

function speechActControlCatalogEntries() {
  return ACTION_INTENT_REGISTRY
    .filter(action => action.visibility === ACTION_INTENT_VISIBILITY.SPEECH_ACT_ONLY)
    .map(action => ({
      id: action.id,
      category: action.category,
      domain: "grounded_question",
      intent: action.intent,
      typedKind: TYPED_KINDS.GROUNDED_QUESTION,
      operationTypes: [action.intent],
      title: action.title,
      summary: `${action.summary} This is documented as a speech-act control concept rather than a standalone planner action.`,
      patterns: action.aliases ?? [],
      examples: action.intent === "correction" ? [
        mappingExample("Actually, use paper_id instead of title", [
          "SET_FILE_KEY_COLUMNS",
          "SET_HYPEREDGE_ENTITY_RULE",
        ], {
          expectedIntent: "correction",
          expectedSpeechAct: "correction",
        }),
        graphExample("Actually add vertex 7 to h2 instead", [{
          type: GRAPH_MUTATION_OPS.ADD_INCIDENCE,
          hyperedgeId: "h2",
          vertexId: "7",
        }], {
          expectedIntent: "add_incidence",
          expectedSpeechAct: "correction",
        }),
        helpExample("How do I correct the last interpretation?", "EXPLAIN_ACTION_COMMAND"),
      ] : [],
      requiredContext: action.requiredContext,
      sideEffect: action.sideEffect,
      confirmation: action.confirmation,
      reversible: true,
      destructive: false,
      worksOffline: true,
      modelPolicy: action.modelPolicy,
      ambiguityNotes: ["Correction phrasing is interpreted against a pending or recent command; ask as a How-do-I question to learn without changing interpretation state."],
      identifierNotes: [],
      relatedCommandIds: action.relatedCommandIds,
      availability: COMMAND_AVAILABILITY.READ_ONLY,
      sinceVersion: CATALOG_CURRENT_VERSION,
    }));
}

export const COMMAND_CATALOG = Object.freeze([
  {
    id: "graph.create-hyperedge",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "add_hyperedge",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.ADD_HYPEREDGE],
    title: "Create a hyperedge",
    summary: "Creates a new hyperedge with explicitly supplied vertices. If vertices are omitted, the assistant asks for them.",
    patterns: ["Create hyperedge <id> with vertices <vertices>", "Make a new group called <id> with <vertices>"],
    examples: [
      graphExample("Create hyperedge h3", [], { expectsClarification: true, expectedSideEffect: SIDE_EFFECT.READ_ONLY }),
      graphExample("Create hyperedge h3 with vertices 8 and 9", [{ type: GRAPH_MUTATION_OPS.ADD_HYPEREDGE, hyperedgeId: "h3", vertices: ["8", "9"] }]),
      graphExample("Make a new group called Researchers with Alice and Bob", [{ type: GRAPH_MUTATION_OPS.ADD_HYPEREDGE, hyperedgeId: "Researchers", vertices: ["Alice", "Bob"] }]),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The new hyperedge ID must not already exist."],
    identifierNotes: ["Quote a literal ID such as \"new group\" if the words are part of the identifier."],
    relatedCommandIds: ["graph.add-incidence", "graph.remove-hyperedge"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.remove-hyperedge",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "remove_hyperedge",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.REMOVE_HYPEREDGE],
    title: "Remove one hyperedge",
    summary: "Removes a named hyperedge from the current graph after preview and confirmation.",
    patterns: ["Remove hyperedge <id>", "Delete the hyperedge named <id>"],
    examples: [
      graphExample("Remove hyperedge h1", [{ type: GRAPH_MUTATION_OPS.REMOVE_HYPEREDGE, hyperedgeId: "h1" }]),
      graphExample("Delete the hyperedge named Researchers", [{ type: GRAPH_MUTATION_OPS.REMOVE_HYPEREDGE, hyperedgeId: "Researchers" }], { fixture: "graph.researchers" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_HYPEREDGE],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["If a name or label is not unique, the assistant asks which hyperedge you mean."],
    identifierNotes: ["Use quotes around hyperedge IDs with spaces."],
    relatedCommandIds: ["graph.create-hyperedge", "graph.clear-graph"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.add-incidence",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "add_incidence",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.ADD_INCIDENCE],
    title: "Add vertices to a hyperedge",
    summary: "Adds one or more vertices to an existing hyperedge. Multiple vertices become multiple ADD_INCIDENCE operations.",
    patterns: ["Add <vertex> to <hyperedge>", "Include <vertices> in <hyperedge>", "Put <vertex> into <hyperedge>"],
    examples: [
      graphExample("Add vertex 6 to h2", [{ type: GRAPH_MUTATION_OPS.ADD_INCIDENCE, hyperedgeId: "h2", vertexId: "6" }]),
      graphExample("Add a vertex 6 to hyperedge h2", [{ type: GRAPH_MUTATION_OPS.ADD_INCIDENCE, hyperedgeId: "h2", vertexId: "6" }]),
      graphExample("Include vertices 6 and 7 in h2", [
        { type: GRAPH_MUTATION_OPS.ADD_INCIDENCE, hyperedgeId: "h2", vertexId: "6" },
        { type: GRAPH_MUTATION_OPS.ADD_INCIDENCE, hyperedgeId: "h2", vertexId: "7" },
      ]),
      graphExample("Put Alice into Researchers", [{ type: GRAPH_MUTATION_OPS.ADD_INCIDENCE, hyperedgeId: "Researchers", vertexId: "Alice" }], { fixture: "graph.researchers" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_HYPEREDGE],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["If the target hyperedge cannot be resolved uniquely, the assistant asks for clarification."],
    identifierNotes: ["`a vertex 6` is normalized to `6`; quote \"a vertex 6\" to preserve that literal text."],
    relatedCommandIds: ["graph.remove-incidence", "graph.create-hyperedge"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.remove-incidence",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "remove_incidence",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.REMOVE_INCIDENCE],
    title: "Remove a vertex from one hyperedge",
    summary: "Removes one membership from one hyperedge while keeping the vertex everywhere else.",
    patterns: ["Remove <vertex> from <hyperedge>", "Take <vertex> out of <hyperedge>"],
    examples: [
      graphExample("Remove vertex 4 from h0", [{ type: GRAPH_MUTATION_OPS.REMOVE_INCIDENCE, hyperedgeId: "h0", vertexId: "4", emptyHyperedgePolicy: "remove_empty" }]),
      graphExample("Take Alice out of Researchers", [{ type: GRAPH_MUTATION_OPS.REMOVE_INCIDENCE, hyperedgeId: "Researchers", vertexId: "Alice", emptyHyperedgePolicy: "remove_empty" }], { fixture: "graph.researchersWithAlice" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_HYPEREDGE, REQUIRED_CONTEXT.EXISTING_VERTEX],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["If removing the vertex would empty the hyperedge, the assistant asks whether to keep or remove the empty hyperedge."],
    identifierNotes: ["This is scoped to one hyperedge; use `everywhere` for global removal."],
    relatedCommandIds: ["graph.remove-vertex-global", "graph.add-incidence"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.remove-vertex-global",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "remove_vertex_global",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.REMOVE_VERTEX_GLOBAL],
    title: "Remove a vertex everywhere",
    summary: "Removes a vertex from every hyperedge in the graph after preview and confirmation.",
    patterns: ["Remove <vertex> everywhere", "Delete <vertex> from the entire graph"],
    examples: [
      graphExample("Remove vertex 4 everywhere", [{ type: GRAPH_MUTATION_OPS.REMOVE_VERTEX_GLOBAL, vertexId: "4", emptyHyperedgePolicy: "remove_empty" }]),
      graphExample("Delete Alice from the entire graph", [{ type: GRAPH_MUTATION_OPS.REMOVE_VERTEX_GLOBAL, vertexId: "Alice", emptyHyperedgePolicy: "remove_empty" }], { fixture: "graph.researchers" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_VERTEX],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The assistant clarifies empty-hyperedge handling when needed."],
    identifierNotes: ["Contrast this with `Remove vertex 4 from h0`, which affects only h0."],
    relatedCommandIds: ["graph.remove-incidence", "graph.undo-last-mutation"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.rename-vertex",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "rename_vertex",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.RENAME_VERTEX],
    title: "Rename a vertex",
    summary: "Renames a vertex everywhere it appears in the graph.",
    patterns: ["Rename vertex <old> to <new>", "Change vertex <old> to <new>"],
    examples: [
      graphExample("Rename vertex 4 to Alice", [{ type: GRAPH_MUTATION_OPS.RENAME_VERTEX, vertexId: "4", newVertexId: "Alice" }]),
      graphExample("Change vertex \"old name\" to \"new name\"", [{ type: GRAPH_MUTATION_OPS.RENAME_VERTEX, vertexId: "old name", newVertexId: "new name" }], { fixture: "graph.named" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_VERTEX],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Quoted old/new names preserve spaces exactly."],
    identifierNotes: ["Quote IDs with spaces or leading words such as vertex/hyperedge."],
    relatedCommandIds: ["graph.rename-hyperedge", "graph.undo-last-mutation"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.rename-hyperedge",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "rename_hyperedge",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.RENAME_HYPEREDGE],
    title: "Rename a hyperedge",
    summary: "Renames a hyperedge ID while keeping its vertices and metadata.",
    patterns: ["Rename <hyperedge> to <new>", "Change hyperedge <old> to <new>"],
    examples: [
      graphExample("Rename h0 to Researchers", [{ type: GRAPH_MUTATION_OPS.RENAME_HYPEREDGE, hyperedgeId: "h0", newHyperedgeId: "Researchers" }]),
      graphExample("Change hyperedge \"Group A\" to \"Research Group A\"", [{ type: GRAPH_MUTATION_OPS.RENAME_HYPEREDGE, hyperedgeId: "Group A", newHyperedgeId: "Research Group A" }], { fixture: "graph.named" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_HYPEREDGE],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The destination hyperedge ID must not collide with another hyperedge."],
    identifierNotes: ["Quote IDs with spaces."],
    relatedCommandIds: ["graph.rename-vertex", "graph.remove-hyperedge"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.set-time",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "set_hyperedge_time",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.SET_HYPEREDGE_TIME],
    title: "Set hyperedge time",
    summary: "Sets or replaces the time metadata for one hyperedge.",
    patterns: ["Set <hyperedge>'s time to <value>", "Set the time of <hyperedge> to <value>"],
    examples: [
      graphExample("Set h2's time to 2026", [{ type: GRAPH_MUTATION_OPS.SET_HYPEREDGE_TIME, hyperedgeId: "h2", time: 2026 }]),
      graphExample("Set the time of h2 to \"2026-08\"", [{ type: GRAPH_MUTATION_OPS.SET_HYPEREDGE_TIME, hyperedgeId: "h2", time: "2026-08" }]),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_HYPEREDGE],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The hyperedge reference must resolve uniquely."],
    identifierNotes: ["Quote non-numeric time strings if you want exact literal text."],
    relatedCommandIds: ["graph.set-weight", "graph.set-attribute"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.set-weight",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "set_hyperedge_weight",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.SET_HYPEREDGE_WEIGHT],
    title: "Set hyperedge weight",
    summary: "Sets numeric weight metadata for one hyperedge. Zero is valid.",
    patterns: ["Set <hyperedge>'s weight to <number>", "Change the weight of <hyperedge> to <number>"],
    examples: [
      graphExample("Set h2's weight to 3.5", [{ type: GRAPH_MUTATION_OPS.SET_HYPEREDGE_WEIGHT, hyperedgeId: "h2", weight: 3.5 }]),
      graphExample("Change the weight of h2 to 0", [{ type: GRAPH_MUTATION_OPS.SET_HYPEREDGE_WEIGHT, hyperedgeId: "h2", weight: 0 }]),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_HYPEREDGE],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Negative or non-numeric weights are rejected by the graph mutation validator."],
    identifierNotes: ["Use the bare hyperedge ID unless the literal ID needs quotes."],
    relatedCommandIds: ["graph.set-time", "graph.set-attribute"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.set-attribute",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "set_hyperedge_attribute",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.SET_HYPEREDGE_ATTRIBUTE],
    title: "Set a hyperedge attribute",
    summary: "Sets one named metadata attribute on one hyperedge.",
    patterns: ["Set attribute <key> on <hyperedge> to <value>", "Set <hyperedge>'s <key> attribute to <value>"],
    examples: [
      graphExample("Set attribute category on h2 to research", [{ type: GRAPH_MUTATION_OPS.SET_HYPEREDGE_ATTRIBUTE, hyperedgeId: "h2", key: "category", value: "research" }]),
      graphExample("Set h2's color attribute to blue", [{ type: GRAPH_MUTATION_OPS.SET_HYPEREDGE_ATTRIBUTE, hyperedgeId: "h2", key: "color", value: "blue" }]),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_HYPEREDGE],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Attribute keys must be simple identifiers such as category or color."],
    identifierNotes: ["Quote values with spaces when exact literal text matters."],
    relatedCommandIds: ["graph.remove-attribute"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.remove-attribute",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "remove_hyperedge_attribute",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.REMOVE_HYPEREDGE_ATTRIBUTE],
    title: "Remove a hyperedge attribute",
    summary: "Deletes one named metadata attribute from one hyperedge.",
    patterns: ["Remove the <key> attribute from <hyperedge>", "Delete attribute <key> from <hyperedge>"],
    examples: [
      graphExample("Remove the category attribute from h2", [{ type: GRAPH_MUTATION_OPS.REMOVE_HYPEREDGE_ATTRIBUTE, hyperedgeId: "h2", key: "category" }]),
      graphExample("Delete attribute color from h2", [{ type: GRAPH_MUTATION_OPS.REMOVE_HYPEREDGE_ATTRIBUTE, hyperedgeId: "h2", key: "color" }]),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.EXISTING_HYPEREDGE],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["If the attribute is absent, the preview reports a no-op rather than silently changing state."],
    identifierNotes: ["Attribute keys are not graph entity IDs."],
    relatedCommandIds: ["graph.set-attribute"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.clear-graph",
    category: COMMAND_CATEGORIES.GRAPH_EDITING,
    domain: "graph_mutation",
    intent: "clear_graph",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.CLEAR_GRAPH],
    title: "Clear the graph",
    summary: "Stages a preview that removes every committed hyperedge. Confirmation is required.",
    patterns: ["Clear the graph", "Remove all hyperedges"],
    examples: [
      graphExample("Clear the graph", [{ type: GRAPH_MUTATION_OPS.CLEAR_GRAPH }]),
      graphExample("Remove all hyperedges", [{ type: GRAPH_MUTATION_OPS.CLEAR_GRAPH }]),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Nothing is removed until you confirm the staged preview."],
    identifierNotes: [],
    relatedCommandIds: ["graph.undo-last-mutation"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "graph.undo-last-mutation",
    category: COMMAND_CATEGORIES.CORRECTIONS_SAFETY,
    domain: "graph_mutation",
    intent: "undo_last_mutation",
    typedKind: TYPED_KINDS.GRAPH_MUTATION_PLAN,
    operationTypes: [GRAPH_MUTATION_OPS.UNDO_LAST_MUTATION],
    title: "Undo the last graph edit",
    summary: "Stages a preview that reverts the most recent committed graph mutation.",
    patterns: ["Undo the last graph edit", "Undo the previous mutation"],
    examples: [
      graphExample("Undo the last graph edit", [{ type: GRAPH_MUTATION_OPS.UNDO_LAST_MUTATION }], { fixture: "graph.history" }),
      graphExample("Undo the previous mutation", [{ type: GRAPH_MUTATION_OPS.UNDO_LAST_MUTATION }], { fixture: "graph.history" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH, REQUIRED_CONTEXT.REVERSIBLE_COMMITTED_HISTORY],
    sideEffect: SIDE_EFFECT.GRAPH_EDIT_PREVIEW,
    confirmation: CONFIRMATION.PREVIEW_CONFIRMATION,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["If there is no mutation history, the assistant reports that nothing can be undone."],
    identifierNotes: [],
    relatedCommandIds: ["graph.clear-graph"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "mapping.file-roles",
    category: COMMAND_CATEGORIES.DATASET_MAPPING,
    domain: "dataset_mapping",
    intent: "mapping_patch",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["SET_FILE_ROLE"],
    title: "Set dataset file roles",
    summary: "Marks uploaded files as vertex, hyperedge, or membership tables in the active DatasetMappingSpec.",
    patterns: ["Use <file> as the vertex table", "Make <file> the hyperedge table", "Treat <file> as the membership table"],
    examples: [
      mappingExample("Use authors.csv as the vertex table", ["SET_FILE_ROLE"]),
      mappingExample("Make papers.csv the hyperedge table", ["SET_FILE_ROLE"]),
      mappingExample("Treat authorships.csv as the membership table", ["SET_FILE_ROLE", "ADD_RELATIONSHIP"]),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Unclear file references trigger clarification instead of guessing."],
    identifierNotes: ["Use exact uploaded filenames when names are similar."],
    relatedCommandIds: ["mapping.key-columns", "mapping.relationships"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "mapping.key-columns",
    category: COMMAND_CATEGORIES.DATASET_MAPPING,
    domain: "dataset_mapping",
    intent: "mapping_patch",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["SET_FILE_KEY_COLUMNS", "SET_VERTEX_ENTITY_RULE", "SET_HYPEREDGE_ENTITY_RULE"],
    title: "Set key columns",
    summary: "Sets vertex or hyperedge key columns and updates the corresponding entity rule.",
    patterns: ["Use <column> as the vertex key", "Use <column> as the hyperedge key", "Use <a> and <b> together as the paper key"],
    examples: [
      mappingExample("Use author_id as the vertex key", ["SET_FILE_KEY_COLUMNS", "SET_VERTEX_ENTITY_RULE"]),
      mappingExample("Use paper_id as the hyperedge key", ["SET_FILE_KEY_COLUMNS", "SET_HYPEREDGE_ENTITY_RULE"]),
      mappingExample("Use year and paper_id together as the paper key", ["SET_FILE_KEY_COLUMNS", "SET_HYPEREDGE_ENTITY_RULE"]),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["If a column appears in multiple files, the assistant asks which file should use it."],
    identifierNotes: ["Column names are resolved against uploaded file headers."],
    relatedCommandIds: ["mapping.file-roles", "mapping.entity-rules"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "mapping.relationships",
    category: COMMAND_CATEGORIES.DATASET_MAPPING,
    domain: "dataset_mapping",
    intent: "mapping_patch",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["ADD_RELATIONSHIP"],
    title: "Add membership relationships",
    summary: "Connects the membership table to vertex and hyperedge tables through verified key columns.",
    patterns: ["<membership>.<column> links to <table>.<column>", "Use <membership file> to connect vertices and hyperedges through IDs"],
    examples: [
      mappingExample("authorships.author_id links to authors.author_id", ["SET_FILE_ROLE", "SET_FILE_ROLE", "ADD_RELATIONSHIP"], { expectedSpeechAct: "declarative_mapping_statement" }),
      mappingExample("authorships.paper_id links to papers.paper_id", ["SET_FILE_ROLE", "SET_FILE_ROLE", "ADD_RELATIONSHIP"], { expectedSpeechAct: "declarative_mapping_statement" }),
      mappingExample("Use authorships.csv to connect authors and papers through their ID columns", ["SET_FILE_ROLE", "SET_FILE_ROLE", "SET_FILE_ROLE", "SET_FILE_KEY_COLUMNS", "SET_VERTEX_ENTITY_RULE", "SET_FILE_KEY_COLUMNS", "SET_HYPEREDGE_ENTITY_RULE", "ADD_RELATIONSHIP"]),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["A valid relationship needs enough context to identify membership, vertex, and hyperedge files."],
    identifierNotes: ["Qualified `file.column` syntax is the least ambiguous form."],
    relatedCommandIds: ["mapping.file-roles", "mapping.key-columns"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "mapping.entity-rules",
    category: COMMAND_CATEGORIES.DATASET_MAPPING,
    domain: "dataset_mapping",
    intent: "mapping_patch",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["SET_VERTEX_ENTITY_RULE", "SET_HYPEREDGE_ENTITY_RULE"],
    title: "Set entity ID and time rules",
    summary: "Sets vertex IDs, hyperedge IDs, or hyperedge time metadata from dataset columns.",
    patterns: ["Use <column> as the hyperedge time", "Use <column> as the hyperedge ID", "Use <column> as the vertex ID"],
    examples: [
      mappingExample("Use year as the hyperedge time", ["SET_HYPEREDGE_ENTITY_RULE"]),
      mappingExample("Use paper_id as the hyperedge ID", ["SET_FILE_KEY_COLUMNS", "SET_HYPEREDGE_ENTITY_RULE"]),
      mappingExample("Use author_id as the vertex ID", ["SET_FILE_KEY_COLUMNS", "SET_VERTEX_ENTITY_RULE"]),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Column references are resolved from the active DatasetMappingSpec."],
    identifierNotes: ["Use file-qualified column names if headers repeat."],
    relatedCommandIds: ["mapping.key-columns", "mapping.relationships"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "mapping.policies",
    category: COMMAND_CATEGORIES.DATASET_MAPPING,
    domain: "dataset_mapping",
    intent: "mapping_patch",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["SET_POLICY"],
    title: "Set supported mapping policies",
    summary: "Sets supported parser policies such as preserving empty hyperedges or deduplicating repeated memberships.",
    patterns: ["Keep papers with no authors", "Deduplicate repeated memberships"],
    examples: [
      mappingExample("Keep papers with no authors", ["SET_POLICY", "SET_POLICY"], { expectedSpeechAct: "imperative_request" }),
      mappingExample("Deduplicate repeated memberships", ["SET_POLICY"]),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Only supported SET_POLICY values are advertised. Missing-ID row dropping is not advertised as a deterministic command in this release."],
    identifierNotes: [],
    relatedCommandIds: ["mapping.relationships"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "grouping.parse-mode",
    category: COMMAND_CATEGORIES.DATASET_GROUPING,
    domain: "dataset_grouping",
    intent: "group_files",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["SET_PARSE_MODE"],
    title: "Treat files together or separately",
    summary: "Controls whether uploaded files are parsed as one dataset, separate datasets, or explicit groups.",
    patterns: ["Treat <files> as one dataset", "Keep <files> in separate groups"],
    examples: [
      mappingExample("Treat authors.csv, papers.csv, and authorships.csv as one dataset", ["SET_PARSE_MODE"], { expectedDomain: "dataset_grouping", expectedSideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT }),
      mappingExample("Keep january.csv and february.csv in separate groups", ["CREATE_GROUP", "MOVE_FILE_TO_GROUP", "SET_PARSE_MODE", "CREATE_GROUP", "MOVE_FILE_TO_GROUP"], { fixture: "mapping.monthly", expectedDomain: "dataset_grouping", expectedSideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT }),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Grouping edits create a mapping revision immediately, but they do not alter the parsed graph."],
    identifierNotes: ["Use exact uploaded filenames."],
    relatedCommandIds: ["grouping.create-group", "grouping.validation-files"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "grouping.create-group",
    category: COMMAND_CATEGORIES.DATASET_GROUPING,
    domain: "dataset_grouping",
    intent: "group_files",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["CREATE_GROUP", "MOVE_FILE_TO_GROUP"],
    title: "Create or populate a dataset group",
    summary: "Creates named dataset groups and moves uploaded files into them.",
    patterns: ["Create a group called <name>", "Move <file> into <group>"],
    examples: [
      mappingExample("Create a group called Publications", ["CREATE_GROUP", "SET_PARSE_MODE"], { expectedDomain: "dataset_grouping", expectedSideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT }),
      mappingExample("Move papers.csv into Publications", ["MOVE_FILE_TO_GROUP", "SET_PARSE_MODE"], { expectedDomain: "dataset_grouping", expectedSideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT }),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["If the group label does not exist, the deterministic patch uses the corresponding stable group id."],
    identifierNotes: ["Group labels are user-facing; group IDs are stable slug IDs."],
    relatedCommandIds: ["grouping.parse-mode", "grouping.validation-files"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "grouping.validation-files",
    category: COMMAND_CATEGORIES.DATASET_GROUPING,
    domain: "dataset_grouping",
    intent: "group_files",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["MARK_VALIDATION_FILE", "MARK_UPDATE_STREAM", "IGNORE_FILE"],
    title: "Mark validation, update, or ignored files",
    summary: "Marks files that should validate output, act as update streams, or be ignored by parser input.",
    patterns: ["Use <file> only for validation", "Mark <file> as an update stream", "Ignore <file>"],
    examples: [
      mappingExample("Ignore notes.csv", ["IGNORE_FILE"], { fixture: "mapping.monthly", expectedDomain: "dataset_grouping", expectedSideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT }),
      mappingExample("Use expected.json only for validation", ["MARK_VALIDATION_FILE"], { expectedDomain: "dataset_grouping", expectedSideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT }),
      mappingExample("Mark graph_updates.csv as an update stream", ["MARK_UPDATE_STREAM"], { fixture: "mapping.monthly", expectedDomain: "dataset_grouping", expectedSideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT }),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_GROUPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Validation-only and ignored files are excluded from parser input."],
    identifierNotes: ["Use exact filenames for safety."],
    relatedCommandIds: ["grouping.parse-mode"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "parser.workflow-status",
    category: COMMAND_CATEGORIES.CUSTOM_PARSER_WORKFLOW,
    domain: "parser_workflow",
    intent: "parser_workflow",
    typedKind: TYPED_KINDS.PARSER_WORKFLOW_OPERATION,
    operationTypes: ["SHOW_WORKFLOW_STATUS"],
    title: "Show parser workflow status",
    summary: "Reports what is ready in the DatasetMappingSpec to parser workflow without changing state.",
    patterns: ["Show the current parser workflow status", "What is ready?", "What should I do next?"],
    examples: [
      parserExample("Show the current parser workflow status", ["SHOW_WORKFLOW_STATUS"], { expectedSideEffect: SIDE_EFFECT.READ_ONLY }),
      parserExample("What is ready?", ["SHOW_WORKFLOW_STATUS"], { expectedSpeechAct: "status_question", expectedSideEffect: SIDE_EFFECT.READ_ONLY }),
      {
        text: "What should I do next?",
        fixture: "parser.plan_ready",
        expectedDomain: "grounded_question",
        expectedTypedKind: TYPED_KINDS.GROUNDED_QUESTION,
        expectedSpeechAct: "status_question",
        expectedSideEffect: SIDE_EFFECT.READ_ONLY,
        expectedIntent: "next_step",
      },
    ],
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["`Continue` chooses the unique next parser-workflow step from current state."],
    identifierNotes: [],
    relatedCommandIds: ["parser.generate-plan", "parser.generate-parser"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "parser.generate-plan",
    category: COMMAND_CATEGORIES.CUSTOM_PARSER_WORKFLOW,
    domain: "parser_workflow",
    intent: "parser_workflow",
    typedKind: TYPED_KINDS.PARSER_WORKFLOW_OPERATION,
    operationTypes: ["GENERATE_TRANSFORMATION_PLAN"],
    title: "Generate the transformation plan",
    summary: "Creates a deterministic transformation plan from the active validated mapping.",
    patterns: ["Generate the transformation plan", "Do not run it; just show the transformation plan"],
    examples: [
      parserExample("Generate the transformation plan", ["GENERATE_TRANSFORMATION_PLAN"]),
      parserExample("Do not run it; just show the transformation plan", ["GENERATE_TRANSFORMATION_PLAN"], { expectedSpeechAct: "imperative_request", negatedRun: true }),
    ],
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["A negated run request must not stage parser execution."],
    identifierNotes: [],
    relatedCommandIds: ["parser.generate-parser", "parser.run-parser"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "parser.generate-parser",
    category: COMMAND_CATEGORIES.CUSTOM_PARSER_WORKFLOW,
    domain: "parser_workflow",
    intent: "parser_workflow",
    typedKind: TYPED_KINDS.PARSER_WORKFLOW_OPERATION,
    operationTypes: ["GENERATE_PARSER_FROM_MAPPING"],
    title: "Generate parser code from mapping",
    summary: "Generates Custom Parser Studio code from the active mapping/plan, but does not run it.",
    patterns: ["Generate the parser from this mapping", "Generate the parser but do not execute it"],
    examples: [
      parserExample("Generate the parser from this mapping", ["GENERATE_PARSER_FROM_MAPPING"], { fixture: "parser.plan_ready" }),
      parserExample("Generate the parser but do not execute it", ["GENERATE_PARSER_FROM_MAPPING"], { negatedRun: true }),
      parserExample("Generate the plan and parser, but do not run it", ["GENERATE_TRANSFORMATION_PLAN", "GENERATE_PARSER_FROM_MAPPING"], { negatedRun: true }),
    ],
    requiredContext: [REQUIRED_CONTEXT.VALID_MAPPING],
    sideEffect: SIDE_EFFECT.WORKFLOW_PREPARATION,
    confirmation: CONFIRMATION.NONE,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Generation and execution are separate. This command does not execute parser code."],
    identifierNotes: [],
    relatedCommandIds: ["parser.generate-plan", "parser.run-parser"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "parser.run-parser",
    category: COMMAND_CATEGORIES.CUSTOM_PARSER_WORKFLOW,
    domain: "parser_workflow",
    intent: "parser_workflow",
    typedKind: TYPED_KINDS.PARSER_WORKFLOW_OPERATION,
    operationTypes: ["RUN_CUSTOM_PARSER_CONFIRMATION"],
    title: "Run the custom parser",
    summary: "Stages a confirmation request before running Custom Parser Studio code.",
    patterns: ["Run the parser", "Execute the generated parser"],
    examples: [
      parserExample("Run the parser", ["RUN_CUSTOM_PARSER_CONFIRMATION"], { fixture: "parser.generated", expectedSideEffect: SIDE_EFFECT.PARSER_RUN_CONFIRMATION }),
    ],
    requiredContext: [REQUIRED_CONTEXT.GENERATED_PARSER],
    sideEffect: SIDE_EFFECT.PARSER_RUN_CONFIRMATION,
    confirmation: CONFIRMATION.RUN_CONFIRMATION,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The code does not run until you confirm."],
    identifierNotes: [],
    relatedCommandIds: ["parser.apply-result"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "parser.apply-result",
    category: COMMAND_CATEGORIES.CUSTOM_PARSER_WORKFLOW,
    domain: "parser_workflow",
    intent: "parser_workflow",
    typedKind: TYPED_KINDS.PARSER_WORKFLOW_OPERATION,
    operationTypes: ["APPLY_CUSTOM_PARSER_RESULT_CONFIRMATION"],
    title: "Apply parser result to graph",
    summary: "Stages a confirmation request before applying a parser result to the graph.",
    patterns: ["Apply the parser result", "Load the parser result"],
    examples: [
      parserExample("Apply the parser result", ["APPLY_CUSTOM_PARSER_RESULT_CONFIRMATION"], { fixture: "parser.result_ready", expectedSideEffect: SIDE_EFFECT.GRAPH_APPLY_CONFIRMATION }),
    ],
    requiredContext: [REQUIRED_CONTEXT.PARSER_RESULT_READY],
    sideEffect: SIDE_EFFECT.GRAPH_APPLY_CONFIRMATION,
    confirmation: CONFIRMATION.APPLY_CONFIRMATION,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The graph is not replaced until you confirm."],
    identifierNotes: [],
    relatedCommandIds: ["parser.run-parser"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "dashboard.statistics",
    category: COMMAND_CATEGORIES.DASHBOARD_NAVIGATION,
    domain: "dashboard_control",
    intent: "NAVIGATE_STATS",
    typedKind: TYPED_KINDS.DASHBOARD_CONTROL_INTENT,
    operationTypes: ["NAVIGATE_STATS"],
    title: "Open Statistics",
    summary: "Navigates to the statistics section for the current graph.",
    patterns: ["Open Statistics", "Show graph stats"],
    examples: [dashboardExample("Open Statistics", "NAVIGATE_STATS")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: [],
    identifierNotes: [],
    relatedCommandIds: ["dashboard.visualization"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "dashboard.visualization",
    category: COMMAND_CATEGORIES.DASHBOARD_NAVIGATION,
    domain: "dashboard_control",
    intent: "NAVIGATE_VISUALIZATION",
    typedKind: TYPED_KINDS.DASHBOARD_CONTROL_INTENT,
    operationTypes: ["NAVIGATE_VISUALIZATION"],
    title: "Open Visualization",
    summary: "Navigates to the graph preview/visualization section.",
    patterns: ["Show Graph Preview", "Go to Visualization"],
    examples: [dashboardExample("Go to Visualization", "NAVIGATE_VISUALIZATION")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: [],
    identifierNotes: [],
    relatedCommandIds: ["dashboard.visual-limit"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "dashboard.runtime-diagnostics",
    category: COMMAND_CATEGORIES.DASHBOARD_NAVIGATION,
    domain: "dashboard_control",
    intent: "OPEN_RUNTIME_DIAGNOSTICS",
    typedKind: TYPED_KINDS.DASHBOARD_CONTROL_INTENT,
    operationTypes: ["OPEN_RUNTIME_DIAGNOSTICS"],
    title: "Open Runtime Diagnostics",
    summary: "Opens the local runtime diagnostics panel.",
    patterns: ["Open Runtime Diagnostics", "Show Ollama diagnostics"],
    examples: [dashboardExample("Open Runtime Diagnostics", "OPEN_RUNTIME_DIAGNOSTICS")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: [],
    identifierNotes: [],
    relatedCommandIds: ["help.model-offline"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "dashboard.visual-limit",
    category: COMMAND_CATEGORIES.DASHBOARD_NAVIGATION,
    domain: "dashboard_control",
    intent: "SET_VISUAL_LIMIT",
    typedKind: TYPED_KINDS.DASHBOARD_CONTROL_INTENT,
    operationTypes: ["SET_VISUAL_LIMIT"],
    title: "Set visualization limit",
    summary: "Changes the number of hyperedges shown in the visualization preview.",
    patterns: ["Set the visual limit to <number>", "Show only the first <number> vertices"],
    examples: [
      dashboardExample("Set the visual limit to 100", "SET_VISUAL_LIMIT", { visualLimit: 100 }),
      dashboardExample("Show only the first 50 vertices", "SET_VISUAL_LIMIT", { visualLimit: 50 }),
    ],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The limit affects visualization display, not the graph data."],
    identifierNotes: [],
    relatedCommandIds: ["dashboard.visualization"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "dashboard.input-route",
    category: COMMAND_CATEGORIES.DASHBOARD_NAVIGATION,
    domain: "dashboard_control",
    intent: "SET_INPUT_ROUTE",
    typedKind: TYPED_KINDS.DASHBOARD_CONTROL_INTENT,
    operationTypes: ["SET_INPUT_ROUTE"],
    title: "Switch input route",
    summary: "Switches the dashboard input route/tab without parsing or replacing the graph.",
    patterns: ["Use <format> input", "Switch to <format>", "Open Custom Parser"],
    examples: [
      dashboardExample("Use H2V input", "SET_INPUT_ROUTE", { route: "H2V" }),
      dashboardExample("Switch to CSR", "SET_INPUT_ROUTE", { route: "CSR" }),
      dashboardExample("Open Custom Parser", "SET_INPUT_ROUTE", { route: "Custom Parser" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Switching routes does not parse data. Parsing may replace the graph and has separate confirmation paths."],
    identifierNotes: [],
    relatedCommandIds: ["formats.supported-inputs"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "dashboard.export-preview",
    category: COMMAND_CATEGORIES.DASHBOARD_NAVIGATION,
    domain: "dashboard_control",
    intent: "SET_EXPORT_FORMAT",
    typedKind: TYPED_KINDS.DASHBOARD_CONTROL_INTENT,
    operationTypes: ["SET_EXPORT_FORMAT"],
    title: "Select export preview",
    summary: "Selects an export preview format for review. It does not automatically download a file. V2V is documented under Mappings as a vertex-to-vertex 2-section projection view, not a native hypergraph incidence representation.",
    patterns: ["Set the export format to <format>", "Preview an <format> export", "Export as CSR CSV"],
    examples: [
      dashboardExample("Set the export format to JSON", "SET_EXPORT_FORMAT", { exportFormat: "JSON" }),
      dashboardExample("Preview an H2V export", "SET_EXPORT_FORMAT", { exportFormat: "H2V" }),
      dashboardExample("Export as CSR CSV", "SET_EXPORT_FORMAT", { exportFormat: "CSR CSV" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.NAVIGATION,
    confirmation: CONFIRMATION.NAVIGATION_ONLY,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Automatic file download remains a confirmation-required operation and is not performed by preview commands."],
    identifierNotes: [],
    relatedCommandIds: ["formats.supported-inputs"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  ...legacyActionCatalogEntries(),
  ...speechActControlCatalogEntries(),
  {
    id: "questions.question-action-contrast",
    category: COMMAND_CATEGORIES.QUESTIONS_EXPLANATIONS,
    domain: "grounded_question",
    intent: "explain_dataset_mapping",
    typedKind: TYPED_KINDS.GROUNDED_QUESTION,
    operationTypes: [],
    title: "Questions are read-only",
    summary: "Question phrasing explains or evaluates without changing mapping, parser, dashboard, or graph state.",
    patterns: ["Would <column> be a better key?", "What would happen if I removed <vertex>?"],
    examples: [
      readOnlyExample("Would paper_id be a better key?", "dataset_mapping", "explain_hypothetical_dataset_mapping"),
      readOnlyExample("What would happen if I removed vertex 4 from h0?", "graph_mutation", "explain_hypothetical_graph_mutation", { fixture: "graph.basic" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Use action phrasing such as `Could you use paper_id as the key?` if you want a mapping edit."],
    identifierNotes: [],
    relatedCommandIds: ["mapping.key-columns", "graph.remove-incidence"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "questions.action-contrast",
    category: COMMAND_CATEGORIES.QUESTIONS_EXPLANATIONS,
    domain: "dataset_mapping",
    intent: "mapping_patch",
    typedKind: TYPED_KINDS.DATASET_MAPPING_PATCH,
    operationTypes: ["SET_FILE_KEY_COLUMNS"],
    title: "Polite action requests still change state",
    summary: "A polite question can still be an action when it asks the assistant to use, set, apply, run, or remove something.",
    patterns: ["Could you use <column> as the key?"],
    examples: [
      mappingExample("Could you use paper_id as the key?", ["SET_FILE_KEY_COLUMNS", "SET_HYPEREDGE_ENTITY_RULE"], { expectedSpeechAct: "polite_interrogative_request" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.UPLOADED_FILES, REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.REVERSIBLE_MAPPING_EDIT,
    confirmation: CONFIRMATION.IMMEDIATE_REVERSIBLE_MAPPING_EDIT,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["If there are several paper_id columns, the assistant asks which file should use it."],
    identifierNotes: [],
    relatedCommandIds: ["questions.question-action-contrast"],
    availability: COMMAND_AVAILABILITY.CHAT_COMMAND,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "help.quick-start",
    category: COMMAND_CATEGORIES.QUICK_START,
    domain: "help_query",
    intent: "SHOW_HELP_OVERVIEW",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["SHOW_HELP_OVERVIEW"],
    title: "Quick Start command suggestions",
    summary: "Shows a small curated set of catalog-backed commands to try first.",
    patterns: [],
    examples: [],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The Quick Start list is derived from stable catalog IDs rather than duplicated UI strings."],
    identifierNotes: [],
    relatedCommandIds: [
      "dashboard.statistics",
      "mapping.file-roles",
      "mapping.key-columns",
      "parser.generate-plan",
      "graph.add-incidence",
      "questions.question-action-contrast",
      "quoted.identifiers",
    ],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "help.overview",
    category: COMMAND_CATEGORIES.QUESTIONS_EXPLANATIONS,
    domain: "help_query",
    intent: "SHOW_HELP_OVERVIEW",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["SHOW_HELP_OVERVIEW"],
    title: "Ask what commands are available",
    summary: "Shows a catalog-driven overview of supported deterministic commands.",
    patterns: ["What commands can I use?", "What can the deterministic chatbot do?"],
    examples: [helpExample("What commands can I use?", "SHOW_HELP_OVERVIEW")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: [],
    identifierNotes: [],
    relatedCommandIds: ["help.find-command", "formats.supported-inputs"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "help.find-command",
    category: COMMAND_CATEGORIES.QUESTIONS_EXPLANATIONS,
    domain: "help_query",
    intent: "FIND_COMMAND",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["FIND_COMMAND", "EXPLAIN_COMMAND", "EXPLAIN_ACTION_COMMAND", "LIST_COMMAND_CATEGORY"],
    title: "Search command help in chat",
    summary: "Finds relevant catalog entries and returns examples without executing them.",
    patterns: ["Show graph commands", "How do I add a vertex?", "How do I remove a vertex everywhere?"],
    examples: [
      helpExample("Show graph commands", "LIST_COMMAND_CATEGORY"),
      helpExample("How do I add a vertex to a hyperedge?", "EXPLAIN_ACTION_COMMAND"),
      helpExample("How do I remove a vertex everywhere?", "EXPLAIN_ACTION_COMMAND"),
      helpExample("Show dataset mapping examples", "LIST_COMMAND_CATEGORY"),
    ],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Help responses may offer example chips, but they never auto-run commands."],
    identifierNotes: [],
    relatedCommandIds: ["help.overview", "graph.add-incidence"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "help.confirmation-list",
    category: COMMAND_CATEGORIES.CORRECTIONS_SAFETY,
    domain: "help_query",
    intent: "LIST_CONFIRMATION_COMMANDS",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["LIST_CONFIRMATION_COMMANDS"],
    title: "List commands that require confirmation",
    summary: "Lists graph previews, parser runs, parser-result application, and other confirmation-gated actions.",
    patterns: ["Which commands require confirmation?"],
    examples: [helpExample("Which commands require confirmation?", "LIST_CONFIRMATION_COMMANDS")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: [],
    identifierNotes: [],
    relatedCommandIds: ["graph.clear-graph", "parser.run-parser", "parser.apply-result"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "help.read-only-list",
    category: COMMAND_CATEGORIES.QUESTIONS_EXPLANATIONS,
    domain: "help_query",
    intent: "LIST_READ_ONLY_COMMANDS",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["LIST_READ_ONLY_COMMANDS"],
    title: "List read-only questions",
    summary: "Lists deterministic questions and explanations that never mutate app state.",
    patterns: ["Show read-only questions"],
    examples: [helpExample("Show read-only questions", "LIST_READ_ONLY_COMMANDS", { expectedSpeechAct: "informational_question" })],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: [],
    identifierNotes: [],
    relatedCommandIds: ["questions.question-action-contrast"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "quoted.identifiers",
    category: COMMAND_CATEGORIES.QUOTED_IDENTIFIERS,
    domain: "help_query",
    intent: "EXPLAIN_QUOTED_IDENTIFIERS",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["EXPLAIN_QUOTED_IDENTIFIERS"],
    title: "How quoted identifiers work",
    summary: "Explains how the deterministic graph grammar strips words like vertex/hyperedge unless they are quoted.",
    patterns: ["How do quoted identifiers work?"],
    examples: [helpExample("How do quoted identifiers work?", "EXPLAIN_QUOTED_IDENTIFIERS")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Unquoted `a vertex 6` is normalized to `6`; quoted `\"a vertex 6\"` is preserved literally."],
    identifierNotes: ["Quote IDs with spaces, punctuation, or words like vertex, node, hyperedge, group."],
    relatedCommandIds: ["graph.add-incidence", "graph.rename-vertex"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "ambiguity.clarification",
    category: COMMAND_CATEGORIES.AMBIGUITY_CLARIFICATION,
    domain: "help_query",
    intent: "EXPLAIN_AMBIGUITY",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["EXPLAIN_AMBIGUITY"],
    title: "Ambiguity and clarification",
    summary: "Explains why the assistant asks follow-up questions instead of guessing when references are ambiguous.",
    patterns: ["Why did the assistant ask a clarification?", "How does ambiguity work?"],
    examples: [helpExample("Why did the assistant ask a clarification?", "EXPLAIN_AMBIGUITY")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Nothing changes while clarification is pending."],
    identifierNotes: [],
    relatedCommandIds: ["quoted.identifiers"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "algorithms.chatbot-support",
    category: COMMAND_CATEGORIES.ALGORITHMS,
    domain: "help_query",
    intent: "EXPLAIN_PANEL_ONLY_FEATURE",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["EXPLAIN_PANEL_ONLY_FEATURE"],
    title: "Can the chatbot run algorithms?",
    summary: "Explains that algorithms are currently panel-only tools, not deterministic chat-executed commands.",
    patterns: ["Can the chatbot run BFS?", "Can the assistant execute algorithms?"],
    examples: [helpExample("Can the chatbot run BFS?", "EXPLAIN_PANEL_ONLY_FEATURE")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["The answer may point to the Algorithms panel, but it does not execute BFS, DFS, Dijkstra, or components from chat."],
    identifierNotes: [],
    relatedCommandIds: ["dashboard.visualization"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "parser.reported-speech",
    category: COMMAND_CATEGORIES.CORRECTIONS_SAFETY,
    domain: "grounded_question",
    intent: "explain_reported_parser_workflow",
    typedKind: TYPED_KINDS.GROUNDED_QUESTION,
    operationTypes: [],
    title: "Reported parser commands are read-only",
    summary: "Reported speech such as a reminder about a previous parser command does not run or stage parser execution.",
    patterns: ["I previously asked you to run the parser"],
    examples: [
      readOnlyExample("I previously asked you to run the parser", "parser_workflow", "explain_reported_parser_workflow", { fixture: "parser.generated", expectedSpeechAct: "reported_command" }),
    ],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Reported speech is intentionally blocked from side effects."],
    identifierNotes: [],
    relatedCommandIds: ["parser.run-parser"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "formats.supported-inputs",
    category: COMMAND_CATEGORIES.INPUT_DATA_FORMATS,
    domain: "dashboard_control",
    intent: "LIST_INPUT_FORMATS",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: ["LIST_INPUT_FORMATS"],
    title: "Supported input data formats",
    summary: "Lists the verified input routes and compact examples.",
    patterns: ["What input formats are supported?"],
    examples: [helpExample("What input formats are supported?", "LIST_INPUT_FORMATS")],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["Export-only formats are not described as input formats."],
    identifierNotes: [],
    relatedCommandIds: ["dashboard.input-route"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  ...INPUT_FORMAT_REFERENCES.map(format => ({
    id: format.id,
    category: COMMAND_CATEGORIES.INPUT_DATA_FORMATS,
    domain: "input_format",
    intent: "format_reference",
    typedKind: TYPED_KINDS.FORMAT_REFERENCE,
    operationTypes: [],
    title: format.name,
    summary: `${format.expectations} Route: ${format.routeLabel}.`,
    patterns: [],
    examples: [],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: [`Auto Detect: ${format.autoDetect ? "supported" : "not advertised as automatic for this format"}.`],
    identifierNotes: [],
    relatedCommandIds: ["dashboard.input-route"],
    availability: COMMAND_AVAILABILITY.FORMAT_REFERENCE,
    sinceVersion: CATALOG_VERSION,
    format,
  })),
  ...ALGORITHM_REGISTRY.map(algorithm => ({
    id: `algorithm.${algorithm.id}`,
    category: COMMAND_CATEGORIES.ALGORITHMS,
    domain: "algorithm_panel",
    intent: "panel_only_algorithm",
    typedKind: TYPED_KINDS.PANEL_ONLY,
    operationTypes: [],
    title: algorithm.label,
    summary: `${algorithm.sub}. Open the Algorithms panel, choose this algorithm, select required vertices, and run it there.`,
    patterns: [],
    examples: [],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH],
    sideEffect: SIDE_EFFECT.PANEL_ONLY,
    confirmation: CONFIRMATION.PANEL_ONLY,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.PANEL_ONLY,
    ambiguityNotes: ["The current deterministic chatbot does not execute this algorithm as a chat command."],
    identifierNotes: [],
    relatedCommandIds: ["dashboard.visualization"],
    availability: COMMAND_AVAILABILITY.PANEL_ONLY,
    sinceVersion: CATALOG_VERSION,
    panelInstructions: "Open the Algorithms panel, choose the algorithm, select required vertices if prompted, and run it.",
  })),
  {
    id: "panel.batch-updates",
    category: COMMAND_CATEGORIES.PANEL_ONLY_FEATURES,
    domain: "batch_updates",
    intent: "panel_only",
    typedKind: TYPED_KINDS.PANEL_ONLY,
    operationTypes: [GRAPH_MUTATION_OPS.COMMIT_BATCH_UPDATES],
    title: "Batch Updates",
    summary: "Batch command preview/commit/discard is available in Advanced Options, not as a free-form chatbot command in this release.",
    patterns: [],
    examples: [],
    requiredContext: [REQUIRED_CONTEXT.LOADED_GRAPH],
    sideEffect: SIDE_EFFECT.PANEL_ONLY,
    confirmation: CONFIRMATION.PANEL_ONLY,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.PANEL_ONLY,
    ambiguityNotes: ["Batch preview pauses conversational graph edits until you commit or discard it."],
    identifierNotes: [],
    relatedCommandIds: ["graph.clear-graph"],
    availability: COMMAND_AVAILABILITY.PANEL_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "panel.mapping-advanced-ops",
    category: COMMAND_CATEGORIES.PANEL_ONLY_FEATURES,
    domain: "dataset_mapping",
    intent: "panel_only_schema_operations",
    typedKind: TYPED_KINDS.PANEL_ONLY,
    operationTypes: PANEL_ONLY_MAPPING_OPERATION_TYPES,
    title: "Advanced mapping patch operations",
    summary: "Some DatasetMappingPatch schema operations are available through mapping editors, repairs, or imported specs but are not deterministic chat commands.",
    patterns: [],
    examples: [],
    requiredContext: [REQUIRED_CONTEXT.ACTIVE_BATCH],
    sideEffect: SIDE_EFFECT.PANEL_ONLY,
    confirmation: CONFIRMATION.PANEL_ONLY,
    reversible: true,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.PANEL_ONLY,
    ambiguityNotes: ["These operation names are documented so schema coverage is honest without advertising unsupported chat phrases."],
    identifierNotes: [],
    relatedCommandIds: ["mapping.file-roles"],
    availability: COMMAND_AVAILABILITY.PANEL_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
  {
    id: "help.model-offline",
    category: COMMAND_CATEGORIES.QUESTIONS_EXPLANATIONS,
    domain: "help_query",
    intent: "offline_model_policy",
    typedKind: TYPED_KINDS.HELP_QUERY,
    operationTypes: [],
    title: "What works without Ollama",
    summary: "The deterministic catalog, dashboard routing, graph previews, mapping edits, parser workflow controls, and Help search work offline without model calls.",
    patterns: [],
    examples: [],
    requiredContext: [REQUIRED_CONTEXT.NONE],
    sideEffect: SIDE_EFFECT.READ_ONLY,
    confirmation: CONFIRMATION.NONE,
    reversible: false,
    worksOffline: true,
    modelPolicy: MODEL_POLICY.ALWAYS_DETERMINISTIC,
    ambiguityNotes: ["A local model may assist unusual phrasing only after deterministic routing does not confidently handle it."],
    identifierNotes: [],
    relatedCommandIds: ["dashboard.runtime-diagnostics"],
    availability: COMMAND_AVAILABILITY.READ_ONLY,
    sinceVersion: CATALOG_VERSION,
  },
]);

export const QUICK_START_COMMAND_IDS = Object.freeze([
  "dashboard.statistics",
  "mapping.file-roles",
  "mapping.key-columns",
  "parser.generate-plan",
  "graph.add-incidence",
  "questions.question-action-contrast",
  "quoted.identifiers",
]);

export const UNSUPPORTED_EXAMPLES_REJECTED = Object.freeze([
  "Run BFS from vertex 1",
  "Search for vertex Alice",
  "Set layout to circular",
  "Drop rows with missing IDs",
  "Download the current graph automatically",
]);

export function getCatalogEntry(id) {
  return COMMAND_CATALOG.find(entry => entry.id === id) ?? null;
}

export function catalogEntriesByCategory(category) {
  return COMMAND_CATALOG.filter(entry => entry.category === category);
}

export function getQuickStartEntries() {
  return QUICK_START_COMMAND_IDS.map(getCatalogEntry).filter(Boolean);
}

export function allCatalogExamples({ includePanelOnly = false } = {}) {
  return COMMAND_CATALOG
    .filter(entry => includePanelOnly || entry.availability !== COMMAND_AVAILABILITY.PANEL_ONLY)
    .flatMap(entry => (entry.examples ?? []).map(example => ({ entry, example })));
}

export function exportPreviewLabels() {
  return Object.values(EXPORT_PREVIEWS).map(item => item.label);
}
