// Verbatim project examples from the supplied PARSER_SNIPPETS.md.
// Dataset 07 is intentionally absent and reserved for held-out evaluation.
export const CUSTOM_PARSER_FEW_SHOTS = Object.freeze([
  {
    "id": "01",
    "title": "Weighted temporal pairs parser",
    "code": "async function parseHypergraph(files, helpers) {\n  const byName = Object.fromEntries(files.map(f => [f.name, f.text]));\n  const nodesText = byName[\"nodes.csv\"];\n  const edgesText = byName[\"edges.csv\"];\n  if (!nodesText || !edgesText) throw new Error(\"Upload nodes.csv and edges.csv together.\");\n\n  const csv = (text) => text.trim().split(/\\r?\\n/).filter(Boolean).map(line => line.split(',').map(x => x.trim()));\n  const nodeRows = csv(nodesText);\n  const nodeHeader = nodeRows.shift();\n  const idIdx = nodeHeader.indexOf('node_id');\n  const labelIdx = nodeHeader.indexOf('label');\n  const typeIdx = nodeHeader.indexOf('type');\n  const nodeMap = new Map(nodeRows.map(r => [r[idIdx], { label: r[labelIdx], type: r[typeIdx] }]));\n\n  const edgeRows = csv(edgesText);\n  const header = edgeRows.shift();\n  const idx = Object.fromEntries(header.map((h, i) => [h, i]));\n  const canonicalHyperedges = edgeRows.map((r, i) => {\n    const s = nodeMap.get(r[idx.source]) || { label: r[idx.source] };\n    const t = nodeMap.get(r[idx.target]) || { label: r[idx.target] };\n    return {\n      id: `weighted_pair_${i + 1}`,\n      vertices: [s.label, t.label],\n      time: r[idx.timestamp],\n      weight: Number(r[idx.weight]),\n      attributes: { relation: r[idx.relation], sourceType: s.type, targetType: t.type }\n    };\n  });\n  return { metadata: { source: \"01-weighted-temporal-pairs\" }, canonicalHyperedges };\n}"
  },
  {
    "id": "02",
    "title": "Event participant split parser",
    "code": "async function parseHypergraph(files, helpers) {\n  const byName = Object.fromEntries(files.map(f => [f.name, f.text]));\n  const eventsText = byName[\"events.csv\"];\n  const participantsText = byName[\"participants.csv\"];\n  if (!eventsText || !participantsText) throw new Error(\"Upload events.csv and participants.csv together.\");\n\n  const csvObjects = (text) => {\n    const lines = text.trim().split(/\\r?\\n/).filter(Boolean);\n    const header = lines.shift().split(',').map(x => x.trim());\n    return lines.map(line => Object.fromEntries(line.split(',').map((v, i) => [header[i], v.trim()])));\n  };\n  const severityWeight = { low: 0.5, medium: 1, high: 2, critical: 3 };\n  const events = Object.fromEntries(csvObjects(eventsText).map(e => [e.event_id, e]));\n  const groups = new Map();\n  for (const p of csvObjects(participantsText)) {\n    if (!groups.has(p.event_id)) groups.set(p.event_id, []);\n    groups.get(p.event_id).push(p.participant_id);\n  }\n  const canonicalHyperedges = [...groups.entries()].map(([eventId, vertices]) => {\n    const e = events[eventId] || {};\n    return {\n      id: eventId,\n      vertices,\n      time: e.year,\n      weight: severityWeight[e.severity] || 1,\n      attributes: { eventName: e.event_name, zone: e.zone, severity: e.severity }\n    };\n  });\n  return { metadata: { source: \"02-event-participant-split\" }, canonicalHyperedges };\n}"
  },
  {
    "id": "03",
    "title": "Adjacency blocks parser",
    "code": "async function parseHypergraph(files, helpers) {\n  const byName = Object.fromEntries(files.map(f => [f.name, f.text]));\n  const verticesText = byName[\"vertices.txt\"];\n  const adjacencyText = byName[\"adjacency.blocks\"];\n  if (!verticesText || !adjacencyText) throw new Error(\"Upload vertices.txt and adjacency.blocks together.\");\n\n  const vertexMap = new Map();\n  for (const line of verticesText.split(/\\r?\\n/)) {\n    const clean = line.trim();\n    if (!clean || clean.startsWith('#')) continue;\n    const [id, label, category] = clean.split('|').map(x => x.trim());\n    vertexMap.set(id, { label, category });\n  }\n\n  const canonicalHyperedges = [];\n  for (const line of adjacencyText.split(/\\r?\\n/)) {\n    const clean = line.trim();\n    if (!clean || clean.startsWith('#')) continue;\n    const [lhs, rhsAll] = clean.split('=>').map(x => x.trim());\n    const [targetsPart, ...metaParts] = rhsAll.split(';').map(x => x.trim());\n    const targetIds = targetsPart.split('|').map(x => x.trim()).filter(Boolean);\n    const meta = Object.fromEntries(metaParts.map(part => part.split('=').map(x => x.trim())));\n    const ids = [lhs, ...targetIds];\n    canonicalHyperedges.push({\n      id: `adj_${canonicalHyperedges.length + 1}`,\n      vertices: ids.map(id => vertexMap.get(id)?.label || id),\n      time: meta.year,\n      weight: 1,\n      attributes: { relation: meta.relation, originalIds: ids }\n    });\n  }\n  return { metadata: { source: \"03-adjacency-blocks\" }, canonicalHyperedges };\n}"
  },
  {
    "id": "04",
    "title": "Layered graph parser",
    "code": "async function parseHypergraph(files, helpers) {\n  const byName = Object.fromEntries(files.map(f => [f.name, f.text]));\n  const layers = JSON.parse(byName[\"layers.json\"] || \"{}\").layers || {};\n  const csvObjects = (text) => {\n    const lines = text.trim().split(/\\r?\\n/).filter(Boolean);\n    const header = lines.shift().split(',').map(x => x.trim());\n    return lines.map(line => Object.fromEntries(line.split(',').map((v, i) => [header[i], v.trim()])));\n  };\n  const canonicalHyperedges = [];\n  for (const file of files) {\n    const match = file.name.match(/^(.*)_edges\\.csv$/);\n    if (!match) continue;\n    const layer = match[1];\n    const layerInfo = layers[layer] || {};\n    for (const row of csvObjects(file.text)) {\n      canonicalHyperedges.push({\n        id: `${layer}_${canonicalHyperedges.length + 1}`,\n        vertices: [row.from, row.to],\n        weight: Number(row.distance || row.quantity || 1) * Number(layerInfo.weightMultiplier || 1),\n        attributes: { layer, layerDescription: layerInfo.description, ...row }\n      });\n    }\n  }\n  return { metadata: { source: \"04-layered-graph\" }, canonicalHyperedges };\n}"
  },
  {
    "id": "05",
    "title": "Update log parser",
    "code": "async function parseHypergraph(files, helpers) {\n  const byName = Object.fromEntries(files.map(f => [f.name, f.text]));\n  if (!byName[\"initial_edges.csv\"] || !byName[\"updates.log\"]) throw new Error(\"Upload initial_edges.csv and updates.log.\");\n  const edgeMap = new Map();\n  const initialLines = byName[\"initial_edges.csv\"].trim().split(/\\r?\\n/).filter(Boolean);\n  initialLines.shift();\n  for (const line of initialLines) {\n    const [edge_id, source, target, kind] = line.split(',').map(x => x.trim());\n    edgeMap.set(edge_id, { edge_id, source, target, kind, time: null });\n  }\n  for (const line of byName[\"updates.log\"].split(/\\r?\\n/)) {\n    const clean = line.trim();\n    if (!clean || clean.startsWith('#')) continue;\n    const [op, edge_id, source, target, kind, time] = clean.split('|').map(x => x.trim());\n    if (op === 'DELETE') edgeMap.delete(edge_id);\n    if (op === 'ADD') edgeMap.set(edge_id, { edge_id, source, target, kind, time });\n  }\n  const canonicalHyperedges = [...edgeMap.values()].map(e => ({\n    id: e.edge_id,\n    vertices: [e.source, e.target],\n    time: e.time,\n    weight: 1,\n    attributes: { kind: e.kind }\n  }));\n  return { metadata: { source: \"05-update-log\", updateApplied: true }, canonicalHyperedges };\n}"
  },
  {
    "id": "06",
    "title": "Matrix coordinate list parser",
    "code": "async function parseHypergraph(files, helpers) {\n  const byName = Object.fromEntries(files.map(f => [f.name, f.text]));\n  const readMap = (text) => new Map(text.trim().split(/\\r?\\n/).filter(Boolean).map(line => {\n    const [idx, label] = line.split(',').map(x => x.trim());\n    return [Number(idx), label];\n  }));\n  const rowMap = readMap(byName[\"row_nodes.txt\"]);\n  const colMap = readMap(byName[\"col_nodes.txt\"]);\n  const canonicalHyperedges = [];\n  for (const line of byName[\"edges.mtx\"].split(/\\r?\\n/)) {\n    const clean = line.trim();\n    if (!clean || clean.startsWith('%')) continue;\n    const parts = clean.split(/\\s+/);\n    if (parts.length === 3 && canonicalHyperedges.length === 0 && Number(parts[2]) > 1) continue; // matrix dimensions line\n    const [r, c, w] = parts.map(Number);\n    if (!Number.isFinite(r) || !Number.isFinite(c)) continue;\n    canonicalHyperedges.push({\n      id: `mtx_${canonicalHyperedges.length + 1}`,\n      vertices: [rowMap.get(r - 1) || `row_${r}`, colMap.get(c - 1) || `col_${c}`],\n      weight: Number(w || 1),\n      attributes: { matrixRow: r, matrixColumn: c }\n    });\n  }\n  return { metadata: { source: \"06-matrix-coordinate-list\" }, canonicalHyperedges };\n}"
  },
  {
    "id": "08",
    "title": "Weird delimiters parser",
    "code": "async function parseHypergraph(files, helpers) {\n  const file = files.find(f => f.name === \"edge_list.weird\") || files[0];\n  const canonicalHyperedges = [];\n  for (const line of file.text.split(/\\r?\\n/)) {\n    const clean = line.trim();\n    if (!clean || clean.startsWith('#')) continue;\n    const [idPart, rest] = clean.split('::').map(x => x.trim());\n    const time = (rest.match(/\\[\\[time=([^\\]]+)\\]\\]/) || [])[1];\n    const weight = Number((rest.match(/\\[\\[weight=([^\\]]+)\\]\\]/) || [])[1] || 1);\n    const verticesPart = rest.replace(/\\[\\[[^\\]]+\\]\\]/g, '').trim();\n    const vertices = verticesPart.split('~~').map(x => x.trim()).filter(Boolean);\n    canonicalHyperedges.push({ id: idPart, vertices, time, weight, attributes: { raw: clean } });\n  }\n  return { metadata: { source: \"08-weird-delimiters\" }, canonicalHyperedges };\n}"
  }
]);

export function selectParserFewShots(files, maximum = 2) {
  const evidence = files.map(f => String(f.name) + " " + String(f.text ?? "").slice(0, 1500)).join(" ");
  const patterns = { "01": /source|target|timestamp|node_id/gi, "02": /event_id|participant|severity/gi, "03": /=>|adjacency|category/gi, "04": /layer|multiplier|transport/gi, "05": /updates|DELETE|initial_edges/gi, "06": /matrix|row_nodes|col_nodes|MatrixMarket/gi, "08": /~~|::/g };
  return CUSTOM_PARSER_FEW_SHOTS.map(example => ({ example, score: [...evidence.matchAll(patterns[example.id])].length }))
    .sort((a, b) => b.score - a.score || a.example.id.localeCompare(b.example.id))
    .slice(0, Math.max(1, Math.min(3, maximum))).map(item => item.example);
}
